syntax = "proto3";

package user_service.auth.v1;

import "core/v1/common.proto";
import "user_service/auth/v1/request.proto";
import "user_service/auth/v1/response.proto";

service AuthService {
  // Authentication
  rpc Login(LoginRequest) returns (AuthResponse);
  rpc LoginWithTwoFactorCode(TwoFactorCodeRequest) returns (AuthResponse);
  rpc Register(RegisterRequest) returns (AuthResponse);

  // Authorization
  rpc Logout(LogoutRequest) returns (core.v1.SuccessResponse);
  rpc LogoutAllDevices(core.v1.EmptyRequest) returns (core.v1.SuccessResponse);

  // Password management
  rpc ChangePassword(ChangePasswordRequest) returns (core.v1.SuccessResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (core.v1.SuccessResponse);

  // Two Factor Authentication
  rpc InitTwoFactorTOTP(core.v1.EmptyRequest) returns (InitTwoFactorTOTPResponse);
  rpc EnableTwoFactorTOTP(TwoFactorTOTPRequest) returns (core.v1.SuccessResponse);

  // Security
  rpc DisableTwoFactor(core.v1.EmptyRequest) returns (core.v1.SuccessResponse);

  // Token management
  rpc RefreshToken(RefreshAccessTokenRequest) returns (RefreshTokenResponse);
  rpc GenerateScopedToken(GenerateScopedTokenRequest) returns (GenerateScopedTokenResponse);

  // Email verification
  rpc RequestEmailVerification(RequestEmailVerificationRequest) returns (core.v1.SuccessResponse);
  rpc RequestPasswordReset(RequestPasswordResetRequest) returns (core.v1.SuccessResponse);
  rpc VerifyEmail(VerifyEmailRequest) returns (core.v1.SuccessResponse);
}
