syntax = "proto3";

package user_service.v1;

import "user_service/v1/account.proto";
import "user_service/v1/models.proto";
import "user_service/v1/profile.proto";

option go_package = "github.com/rijum8906/relay/proto/user_service/v1;userservice";

// Authentication service
service AuthService {
  // Sign up new user
  // buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
  // buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
  rpc Signup(SignupRequest) returns (AuthResponse);

  // Sign in existing user
  // buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
  // buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
  rpc Signin(SigninRequest) returns (AuthResponse);

  // Sign out
  rpc Signout(SignoutRequest) returns (SignoutResponse);

  // Request email verification
  rpc RequestEmailVerfication(RequestEmailVerificationRequest) returns (RequestEmailVerificationResponse);

  // Verify email
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse);

  // Request password reset
  rpc RequestPasswordReset(RequestPasswordResetRequest) returns (RequestPasswordResetResponse);

  // Reset password
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);

  // Change Password
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);

  rpc GetMyAccount(GetMyAccountRequest) returns (GetMyAccountResponse);

  rpc GetMyProfile(GetMyProfileRequest) returns (GetMyProfileResponse);

  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);

  rpc DeleteProfile(DeleteProfileRequest) returns (DeleteProfileResponse);

  rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);

  rpc GenerateScopedToken(GenerateScopedTokenRequest) returns (GenerateScopedTokenResponse);
}
