syntax = "proto3";

package user_service.v1;

import "buf/validate/validate.proto";
import "common/v1/common.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/rijum8906/relay/proto/user_service/v1;userservice";

// Update Profile
message UpdateProfileRequest {
  common.v1.String first_name = 1 [(buf.validate.field).required = true];
  common.v1.String last_name = 2 [(buf.validate.field).required = true];
  common.v1.String avatar_url = 3 [(buf.validate.field).required = true];
  common.v1.String display_name = 4 [(buf.validate.field).required = true];
  common.v1.RequestMetadata metadata = 5 [(buf.validate.field).required = true];
}

message UpdateProfileResponse {
  common.v1.String first_name = 1 [(buf.validate.field).required = true];
  common.v1.String last_name = 2 [(buf.validate.field).required = true];
  common.v1.String avatar_url = 3 [(buf.validate.field).required = true];
  common.v1.String display_name = 4 [(buf.validate.field).required = true];
}

// Delete Profile
message DeleteProfileRequest {
  common.v1.UUID id = 1 [(buf.validate.field).required = true];
  common.v1.String token = 2 [(buf.validate.field).required = true];
  common.v1.RequestMetadata metadata = 3 [(buf.validate.field).required = true];
}

message DeleteProfileResponse {
  bool success = 1 [(buf.validate.field).required = true];
}

// Get My Profile
message GetMyProfileRequest {
  common.v1.RequestMetadata metadata = 1 [(buf.validate.field).required = true];
}

message GetMyProfileResponse {
  common.v1.UUID id = 1 [(buf.validate.field).required = true];
  common.v1.String first_name = 2 [(buf.validate.field).required = true];
  common.v1.String last_name = 3 [(buf.validate.field).required = true];
  common.v1.String avatar_url = 4 [(buf.validate.field).required = true];
  common.v1.String display_name = 5 [(buf.validate.field).required = true];
  google.protobuf.Timestamp created_at = 7 [(buf.validate.field).required = true];
  google.protobuf.Timestamp updated_at = 8 [(buf.validate.field).required = true];
}
