// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthRespose struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type SigninInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
