// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/auth/v1/messages.proto

package authv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/rijum8906/relay/packages/pb/common/v1"
	v11 "github.com/rijum8906/relay/packages/pb/user_service/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *v1.Email              `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      *v1.Password           `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     *v1.Name               `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *v1.Name               `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SignupRequest) GetEmail() *v1.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *SignupRequest) GetPassword() *v1.Password {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *SignupRequest) GetFirstName() *v1.Name {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *SignupRequest) GetLastName() *v1.Name {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *SignupRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SignupResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Result        *v11.AuthenticationResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SignupResponse) GetResult() *v11.AuthenticationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type SigninRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *v1.Email              `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      *v1.Password           `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigninRequest) Reset() {
	*x = SigninRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigninRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninRequest) ProtoMessage() {}

func (x *SigninRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninRequest.ProtoReflect.Descriptor instead.
func (*SigninRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SigninRequest) GetEmail() *v1.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *SigninRequest) GetPassword() *v1.Password {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *SigninRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SigninResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Result        *v11.AuthenticationResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigninResponse) Reset() {
	*x = SigninResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigninResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninResponse) ProtoMessage() {}

func (x *SigninResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninResponse.ProtoReflect.Descriptor instead.
func (*SigninResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SigninResponse) GetResult() *v11.AuthenticationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *LogoutRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LogoutAllDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutAllDeviceRequest) Reset() {
	*x = LogoutAllDeviceRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAllDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAllDeviceRequest) ProtoMessage() {}

func (x *LogoutAllDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAllDeviceRequest.ProtoReflect.Descriptor instead.
func (*LogoutAllDeviceRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutAllDeviceRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *LogoutAllDeviceRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogoutAllDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  uint32                 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutAllDeviceResponse) Reset() {
	*x = LogoutAllDeviceResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutAllDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutAllDeviceResponse) ProtoMessage() {}

func (x *LogoutAllDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutAllDeviceResponse.ProtoReflect.Descriptor instead.
func (*LogoutAllDeviceResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutAllDeviceResponse) GetRevokedCount() uint32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

type RequestEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *v1.Email              `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationRequest) Reset() {
	*x = RequestEmailVerificationRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationRequest) ProtoMessage() {}

func (x *RequestEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *RequestEmailVerificationRequest) GetEmail() *v1.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *RequestEmailVerificationRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RequestEmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationResponse) Reset() {
	*x = RequestEmailVerificationResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationResponse) ProtoMessage() {}

func (x *RequestEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RequestEmailVerificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopedToken   *v1.Token              `protobuf:"bytes,1,opt,name=scoped_token,json=scopedToken,proto3" json:"scoped_token,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyEmailRequest) GetScopedToken() *v1.Token {
	if x != nil {
		return x.ScopedToken
	}
	return nil
}

func (x *VerifyEmailRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type VerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *v11.Account           `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailResponse) Reset() {
	*x = VerifyEmailResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailResponse) ProtoMessage() {}

func (x *VerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyEmailResponse) GetAccount() *v11.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type RequestPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *v1.Email              `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetRequest) Reset() {
	*x = RequestPasswordResetRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetRequest) ProtoMessage() {}

func (x *RequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *RequestPasswordResetRequest) GetEmail() *v1.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *RequestPasswordResetRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RequestPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetResponse) Reset() {
	*x = RequestPasswordResetResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetResponse) ProtoMessage() {}

func (x *RequestPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *RequestPasswordResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopedToken   *v1.Token              `protobuf:"bytes,1,opt,name=scoped_token,json=scopedToken,proto3" json:"scoped_token,omitempty"`
	NewPassword   *v1.Password           `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordRequest) GetScopedToken() *v1.Token {
	if x != nil {
		return x.ScopedToken
	}
	return nil
}

func (x *ResetPasswordRequest) GetNewPassword() *v1.Password {
	if x != nil {
		return x.NewPassword
	}
	return nil
}

func (x *ResetPasswordRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CurrentPassword *v1.Password           `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     *v1.Password           `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Metadata        *v1.RequestMetadata    `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ChangePasswordRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *ChangePasswordRequest) GetCurrentPassword() *v1.Password {
	if x != nil {
		return x.CurrentPassword
	}
	return nil
}

func (x *ChangePasswordRequest) GetNewPassword() *v1.Password {
	if x != nil {
		return x.NewPassword
	}
	return nil
}

func (x *ChangePasswordRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GetSessionsRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *GetSessionsRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*v11.Session         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *GetSessionsResponse) GetSessions() []*v11.Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	SessionId     *v1.UUID               `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *RevokeSessionRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *RevokeSessionRequest) GetSessionId() *v1.UUID {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RevokeSessionRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeAllSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllSessionsRequest) Reset() {
	*x = RevokeAllSessionsRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllSessionsRequest) ProtoMessage() {}

func (x *RevokeAllSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllSessionsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *RevokeAllSessionsRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *RevokeAllSessionsRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RevokeAllSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  uint32                 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllSessionsResponse) Reset() {
	*x = RevokeAllSessionsResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllSessionsResponse) ProtoMessage() {}

func (x *RevokeAllSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeAllSessionsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *RevokeAllSessionsResponse) GetRevokedCount() uint32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

type GenerateScopedTokenRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Scope         v11.ScopedTokenScope       `protobuf:"varint,1,opt,name=scope,proto3,enum=user_service.v1.ScopedTokenScope" json:"scope,omitempty"`
	SubjectType   v11.ScopedTokenSubjectType `protobuf:"varint,2,opt,name=subject_type,json=subjectType,proto3,enum=user_service.v1.ScopedTokenSubjectType" json:"subject_type,omitempty"`
	Subject       *v1.String                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Password      *v1.Password               `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Metadata      *v1.RequestMetadata        `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScopedTokenRequest) Reset() {
	*x = GenerateScopedTokenRequest{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScopedTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScopedTokenRequest) ProtoMessage() {}

func (x *GenerateScopedTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScopedTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateScopedTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{24}
}

func (x *GenerateScopedTokenRequest) GetScope() v11.ScopedTokenScope {
	if x != nil {
		return x.Scope
	}
	return v11.ScopedTokenScope(0)
}

func (x *GenerateScopedTokenRequest) GetSubjectType() v11.ScopedTokenSubjectType {
	if x != nil {
		return x.SubjectType
	}
	return v11.ScopedTokenSubjectType(0)
}

func (x *GenerateScopedTokenRequest) GetSubject() *v1.String {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GenerateScopedTokenRequest) GetPassword() *v1.Password {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *GenerateScopedTokenRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerateScopedTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *v1.Token              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScopedTokenResponse) Reset() {
	*x = GenerateScopedTokenResponse{}
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScopedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScopedTokenResponse) ProtoMessage() {}

func (x *GenerateScopedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_auth_v1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScopedTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateScopedTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_service_auth_v1_messages_proto_rawDescGZIP(), []int{25}
}

func (x *GenerateScopedTokenResponse) GetToken() *v1.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_user_service_auth_v1_messages_proto protoreflect.FileDescriptor

const file_user_service_auth_v1_messages_proto_rawDesc = "" +
	"\n" +
	"#user_service/auth/v1/messages.proto\x12\x14user_service.auth.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x1cuser_service/v1/common.proto\x1a\x1cuser_service/v1/models.proto\"\xa6\x02\n" +
	"\rSignupRequest\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x10.common.v1.EmailB\x06\xbaH\x03\xc8\x01\x01R\x05email\x127\n" +
	"\bpassword\x18\x02 \x01(\v2\x13.common.v1.PasswordB\x06\xbaH\x03\xc8\x01\x01R\bpassword\x126\n" +
	"\n" +
	"first_name\x18\x03 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\tfirstName\x124\n" +
	"\tlast_name\x18\x04 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\blastName\x12>\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"W\n" +
	"\x0eSignupResponse\x12E\n" +
	"\x06result\x18\x01 \x01(\v2%.user_service.v1.AuthenticationResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\"\xb8\x01\n" +
	"\rSigninRequest\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x10.common.v1.EmailB\x06\xbaH\x03\xc8\x01\x01R\x05email\x127\n" +
	"\bpassword\x18\x02 \x01(\v2\x13.common.v1.PasswordB\x06\xbaH\x03\xc8\x01\x01R\bpassword\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"W\n" +
	"\x0eSigninResponse\x12E\n" +
	"\x06result\x18\x01 \x01(\v2%.user_service.v1.AuthenticationResultB\x06\xbaH\x03\xc8\x01\x01R\x06result\"\x8c\x01\n" +
	"\rLogoutRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x95\x01\n" +
	"\x16LogoutAllDeviceRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\">\n" +
	"\x17LogoutAllDeviceResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\rR\frevokedCount\"\x91\x01\n" +
	"\x1fRequestEmailVerificationRequest\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x10.common.v1.EmailB\x06\xbaH\x03\xc8\x01\x01R\x05email\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"<\n" +
	" RequestEmailVerificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x12VerifyEmailRequest\x12;\n" +
	"\fscoped_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vscopedToken\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"Q\n" +
	"\x13VerifyEmailResponse\x12:\n" +
	"\aaccount\x18\x01 \x01(\v2\x18.user_service.v1.AccountB\x06\xbaH\x03\xc8\x01\x01R\aaccount\"\x8d\x01\n" +
	"\x1bRequestPasswordResetRequest\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x10.common.v1.EmailB\x06\xbaH\x03\xc8\x01\x01R\x05email\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"8\n" +
	"\x1cRequestPasswordResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd3\x01\n" +
	"\x14ResetPasswordRequest\x12;\n" +
	"\fscoped_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vscopedToken\x12>\n" +
	"\fnew_password\x18\x02 \x01(\v2\x13.common.v1.PasswordB\x06\xbaH\x03\xc8\x01\x01R\vnewPassword\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"1\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9c\x02\n" +
	"\x15ChangePasswordRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12F\n" +
	"\x10current_password\x18\x02 \x01(\v2\x13.common.v1.PasswordB\x06\xbaH\x03\xc8\x01\x01R\x0fcurrentPassword\x12>\n" +
	"\fnew_password\x18\x03 \x01(\v2\x13.common.v1.PasswordB\x06\xbaH\x03\xc8\x01\x01R\vnewPassword\x12>\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x12GetSessionsRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"K\n" +
	"\x13GetSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.user_service.v1.SessionR\bsessions\"\xcb\x01\n" +
	"\x14RevokeSessionRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x126\n" +
	"\n" +
	"session_id\x18\x02 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tsessionId\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x97\x01\n" +
	"\x18RevokeAllSessionsRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"@\n" +
	"\x19RevokeAllSessionsResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\rR\frevokedCount\"\xd9\x02\n" +
	"\x1aGenerateScopedTokenRequest\x127\n" +
	"\x05scope\x18\x01 \x01(\x0e2!.user_service.v1.ScopedTokenScopeR\x05scope\x12J\n" +
	"\fsubject_type\x18\x02 \x01(\x0e2'.user_service.v1.ScopedTokenSubjectTypeR\vsubjectType\x123\n" +
	"\asubject\x18\x03 \x01(\v2\x11.common.v1.StringB\x06\xbaH\x03\xc8\x01\x01R\asubject\x124\n" +
	"\bpassword\x18\x04 \x01(\v2\x13.common.v1.PasswordH\x00R\bpassword\x88\x01\x01\x12>\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadataB\v\n" +
	"\t_password\"M\n" +
	"\x1bGenerateScopedTokenResponse\x12.\n" +
	"\x05token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\x05tokenB\xdb\x01\n" +
	"\x18com.user_service.auth.v1B\rMessagesProtoP\x01ZBgithub.com/rijum8906/relay/packages/pb/user_service/auth/v1;authv1\xa2\x02\x03UAX\xaa\x02\x13UserService.Auth.V1\xca\x02\x13UserService\\Auth\\V1\xe2\x02\x1fUserService\\Auth\\V1\\GPBMetadata\xea\x02\x15UserService::Auth::V1b\x06proto3"

var (
	file_user_service_auth_v1_messages_proto_rawDescOnce sync.Once
	file_user_service_auth_v1_messages_proto_rawDescData []byte
)

func file_user_service_auth_v1_messages_proto_rawDescGZIP() []byte {
	file_user_service_auth_v1_messages_proto_rawDescOnce.Do(func() {
		file_user_service_auth_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_auth_v1_messages_proto_rawDesc), len(file_user_service_auth_v1_messages_proto_rawDesc)))
	})
	return file_user_service_auth_v1_messages_proto_rawDescData
}

var file_user_service_auth_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_user_service_auth_v1_messages_proto_goTypes = []any{
	(*SignupRequest)(nil),                    // 0: user_service.auth.v1.SignupRequest
	(*SignupResponse)(nil),                   // 1: user_service.auth.v1.SignupResponse
	(*SigninRequest)(nil),                    // 2: user_service.auth.v1.SigninRequest
	(*SigninResponse)(nil),                   // 3: user_service.auth.v1.SigninResponse
	(*LogoutRequest)(nil),                    // 4: user_service.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),                   // 5: user_service.auth.v1.LogoutResponse
	(*LogoutAllDeviceRequest)(nil),           // 6: user_service.auth.v1.LogoutAllDeviceRequest
	(*LogoutAllDeviceResponse)(nil),          // 7: user_service.auth.v1.LogoutAllDeviceResponse
	(*RequestEmailVerificationRequest)(nil),  // 8: user_service.auth.v1.RequestEmailVerificationRequest
	(*RequestEmailVerificationResponse)(nil), // 9: user_service.auth.v1.RequestEmailVerificationResponse
	(*VerifyEmailRequest)(nil),               // 10: user_service.auth.v1.VerifyEmailRequest
	(*VerifyEmailResponse)(nil),              // 11: user_service.auth.v1.VerifyEmailResponse
	(*RequestPasswordResetRequest)(nil),      // 12: user_service.auth.v1.RequestPasswordResetRequest
	(*RequestPasswordResetResponse)(nil),     // 13: user_service.auth.v1.RequestPasswordResetResponse
	(*ResetPasswordRequest)(nil),             // 14: user_service.auth.v1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),            // 15: user_service.auth.v1.ResetPasswordResponse
	(*ChangePasswordRequest)(nil),            // 16: user_service.auth.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),           // 17: user_service.auth.v1.ChangePasswordResponse
	(*GetSessionsRequest)(nil),               // 18: user_service.auth.v1.GetSessionsRequest
	(*GetSessionsResponse)(nil),              // 19: user_service.auth.v1.GetSessionsResponse
	(*RevokeSessionRequest)(nil),             // 20: user_service.auth.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),            // 21: user_service.auth.v1.RevokeSessionResponse
	(*RevokeAllSessionsRequest)(nil),         // 22: user_service.auth.v1.RevokeAllSessionsRequest
	(*RevokeAllSessionsResponse)(nil),        // 23: user_service.auth.v1.RevokeAllSessionsResponse
	(*GenerateScopedTokenRequest)(nil),       // 24: user_service.auth.v1.GenerateScopedTokenRequest
	(*GenerateScopedTokenResponse)(nil),      // 25: user_service.auth.v1.GenerateScopedTokenResponse
	(*v1.Email)(nil),                         // 26: common.v1.Email
	(*v1.Password)(nil),                      // 27: common.v1.Password
	(*v1.Name)(nil),                          // 28: common.v1.Name
	(*v1.RequestMetadata)(nil),               // 29: common.v1.RequestMetadata
	(*v11.AuthenticationResult)(nil),         // 30: user_service.v1.AuthenticationResult
	(*v1.Token)(nil),                         // 31: common.v1.Token
	(*v11.Account)(nil),                      // 32: user_service.v1.Account
	(*v11.Session)(nil),                      // 33: user_service.v1.Session
	(*v1.UUID)(nil),                          // 34: common.v1.UUID
	(v11.ScopedTokenScope)(0),                // 35: user_service.v1.ScopedTokenScope
	(v11.ScopedTokenSubjectType)(0),          // 36: user_service.v1.ScopedTokenSubjectType
	(*v1.String)(nil),                        // 37: common.v1.String
}
var file_user_service_auth_v1_messages_proto_depIdxs = []int32{
	26, // 0: user_service.auth.v1.SignupRequest.email:type_name -> common.v1.Email
	27, // 1: user_service.auth.v1.SignupRequest.password:type_name -> common.v1.Password
	28, // 2: user_service.auth.v1.SignupRequest.first_name:type_name -> common.v1.Name
	28, // 3: user_service.auth.v1.SignupRequest.last_name:type_name -> common.v1.Name
	29, // 4: user_service.auth.v1.SignupRequest.metadata:type_name -> common.v1.RequestMetadata
	30, // 5: user_service.auth.v1.SignupResponse.result:type_name -> user_service.v1.AuthenticationResult
	26, // 6: user_service.auth.v1.SigninRequest.email:type_name -> common.v1.Email
	27, // 7: user_service.auth.v1.SigninRequest.password:type_name -> common.v1.Password
	29, // 8: user_service.auth.v1.SigninRequest.metadata:type_name -> common.v1.RequestMetadata
	30, // 9: user_service.auth.v1.SigninResponse.result:type_name -> user_service.v1.AuthenticationResult
	31, // 10: user_service.auth.v1.LogoutRequest.access_token:type_name -> common.v1.Token
	29, // 11: user_service.auth.v1.LogoutRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 12: user_service.auth.v1.LogoutAllDeviceRequest.access_token:type_name -> common.v1.Token
	29, // 13: user_service.auth.v1.LogoutAllDeviceRequest.metadata:type_name -> common.v1.RequestMetadata
	26, // 14: user_service.auth.v1.RequestEmailVerificationRequest.email:type_name -> common.v1.Email
	29, // 15: user_service.auth.v1.RequestEmailVerificationRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 16: user_service.auth.v1.VerifyEmailRequest.scoped_token:type_name -> common.v1.Token
	29, // 17: user_service.auth.v1.VerifyEmailRequest.metadata:type_name -> common.v1.RequestMetadata
	32, // 18: user_service.auth.v1.VerifyEmailResponse.account:type_name -> user_service.v1.Account
	26, // 19: user_service.auth.v1.RequestPasswordResetRequest.email:type_name -> common.v1.Email
	29, // 20: user_service.auth.v1.RequestPasswordResetRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 21: user_service.auth.v1.ResetPasswordRequest.scoped_token:type_name -> common.v1.Token
	27, // 22: user_service.auth.v1.ResetPasswordRequest.new_password:type_name -> common.v1.Password
	29, // 23: user_service.auth.v1.ResetPasswordRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 24: user_service.auth.v1.ChangePasswordRequest.access_token:type_name -> common.v1.Token
	27, // 25: user_service.auth.v1.ChangePasswordRequest.current_password:type_name -> common.v1.Password
	27, // 26: user_service.auth.v1.ChangePasswordRequest.new_password:type_name -> common.v1.Password
	29, // 27: user_service.auth.v1.ChangePasswordRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 28: user_service.auth.v1.GetSessionsRequest.access_token:type_name -> common.v1.Token
	29, // 29: user_service.auth.v1.GetSessionsRequest.metadata:type_name -> common.v1.RequestMetadata
	33, // 30: user_service.auth.v1.GetSessionsResponse.sessions:type_name -> user_service.v1.Session
	31, // 31: user_service.auth.v1.RevokeSessionRequest.access_token:type_name -> common.v1.Token
	34, // 32: user_service.auth.v1.RevokeSessionRequest.session_id:type_name -> common.v1.UUID
	29, // 33: user_service.auth.v1.RevokeSessionRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 34: user_service.auth.v1.RevokeAllSessionsRequest.access_token:type_name -> common.v1.Token
	29, // 35: user_service.auth.v1.RevokeAllSessionsRequest.metadata:type_name -> common.v1.RequestMetadata
	35, // 36: user_service.auth.v1.GenerateScopedTokenRequest.scope:type_name -> user_service.v1.ScopedTokenScope
	36, // 37: user_service.auth.v1.GenerateScopedTokenRequest.subject_type:type_name -> user_service.v1.ScopedTokenSubjectType
	37, // 38: user_service.auth.v1.GenerateScopedTokenRequest.subject:type_name -> common.v1.String
	27, // 39: user_service.auth.v1.GenerateScopedTokenRequest.password:type_name -> common.v1.Password
	29, // 40: user_service.auth.v1.GenerateScopedTokenRequest.metadata:type_name -> common.v1.RequestMetadata
	31, // 41: user_service.auth.v1.GenerateScopedTokenResponse.token:type_name -> common.v1.Token
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_user_service_auth_v1_messages_proto_init() }
func file_user_service_auth_v1_messages_proto_init() {
	if File_user_service_auth_v1_messages_proto != nil {
		return
	}
	file_user_service_auth_v1_messages_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_auth_v1_messages_proto_rawDesc), len(file_user_service_auth_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_auth_v1_messages_proto_goTypes,
		DependencyIndexes: file_user_service_auth_v1_messages_proto_depIdxs,
		MessageInfos:      file_user_service_auth_v1_messages_proto_msgTypes,
	}.Build()
	File_user_service_auth_v1_messages_proto = out.File
	file_user_service_auth_v1_messages_proto_goTypes = nil
	file_user_service_auth_v1_messages_proto_depIdxs = nil
}
