services:
  # postgres
  postgres:
    image: postgres:14.22-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

    # redis
  redis:
    image: redis:8.4.2-trixie
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  # user-service
  user-service:
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    ports:
      - "8906:8906"
    depends_on:
      - "postgres"
      - "redis"

  # graphql-gateway
  graphql-gateway:
    build:
      context: .
      dockerfile: ./services/graphql-gateway/Dockerfile
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - "user-service"

  # web-v2
  web-v2:
    build:
      context: ./services/web-v2
      dockerfile: Dockerfile
    environment:
      GRAPHQL_URL: "http://localhost:8080/query"
    ports:
      - "3000:3000"
    depends_on:
      - graphql-gateway

volumes:
  pg_data:
  redis:
