// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/errors.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Client errors (4xx)
	ErrorCode_ERROR_CODE_BAD_REQUEST       ErrorCode = 40000
	ErrorCode_ERROR_CODE_UNAUTHORIZED      ErrorCode = 40100
	ErrorCode_ERROR_CODE_FORBIDDEN         ErrorCode = 40300
	ErrorCode_ERROR_CODE_NOT_FOUND         ErrorCode = 40400
	ErrorCode_ERROR_CODE_CONFLICT          ErrorCode = 40900
	ErrorCode_ERROR_CODE_VALIDATION        ErrorCode = 42200
	ErrorCode_ERROR_CODE_TOO_MANY_REQUESTS ErrorCode = 42900
	// Server errors (5xx)
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 50000
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE ErrorCode = 50300
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED   ErrorCode = 50400
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:     "ERROR_CODE_UNSPECIFIED",
		40000: "ERROR_CODE_BAD_REQUEST",
		40100: "ERROR_CODE_UNAUTHORIZED",
		40300: "ERROR_CODE_FORBIDDEN",
		40400: "ERROR_CODE_NOT_FOUND",
		40900: "ERROR_CODE_CONFLICT",
		42200: "ERROR_CODE_VALIDATION",
		42900: "ERROR_CODE_TOO_MANY_REQUESTS",
		50000: "ERROR_CODE_INTERNAL",
		50300: "ERROR_CODE_SERVICE_UNAVAILABLE",
		50400: "ERROR_CODE_DEADLINE_EXCEEDED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_BAD_REQUEST":         40000,
		"ERROR_CODE_UNAUTHORIZED":        40100,
		"ERROR_CODE_FORBIDDEN":           40300,
		"ERROR_CODE_NOT_FOUND":           40400,
		"ERROR_CODE_CONFLICT":            40900,
		"ERROR_CODE_VALIDATION":          42200,
		"ERROR_CODE_TOO_MANY_REQUESTS":   42900,
		"ERROR_CODE_INTERNAL":            50000,
		"ERROR_CODE_SERVICE_UNAVAILABLE": 50300,
		"ERROR_CODE_DEADLINE_EXCEEDED":   50400,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

// Validation error details
type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_common_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidationError) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Error details for responses
type ErrorDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=common.v1.ErrorCode" json:"code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId        string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ValidationErrors []*ValidationError     `protobuf:"bytes,4,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_common_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetails) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ErrorDetails) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *ErrorDetails) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Extended error info
type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_common_v1_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ErrorInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Error response wrapper
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorDetails          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_common_v1_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_common_v1_errors_proto protoreflect.FileDescriptor

const file_common_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/errors.proto\x12\tcommon.v1\"k\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\xba\x02\n" +
	"\fErrorDetails\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.common.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12G\n" +
	"\x11validation_errors\x18\x04 \x03(\v2\x1a.common.v1.ValidationErrorR\x10validationErrors\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.common.v1.ErrorDetails.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\tErrorInfo\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".common.v1.ErrorInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\rErrorResponse\x12-\n" +
	"\x05error\x18\x01 \x01(\v2\x17.common.v1.ErrorDetailsR\x05error*\xdd\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\xc0\xb8\x02\x12\x1d\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\xa4\xb9\x02\x12\x1a\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\xec\xba\x02\x12\x1a\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10л\x02\x12\x19\n" +
	"\x13ERROR_CODE_CONFLICT\x10Ŀ\x02\x12\x1b\n" +
	"\x15ERROR_CODE_VALIDATION\x10\xd8\xc9\x02\x12\"\n" +
	"\x1cERROR_CODE_TOO_MANY_REQUESTS\x10\x94\xcf\x02\x12\x19\n" +
	"\x13ERROR_CODE_INTERNAL\x10І\x03\x12$\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10\xfc\x88\x03\x12\"\n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\xe0\x89\x03B\x99\x01\n" +
	"\rcom.common.v1B\vErrorsProtoP\x01Z6github.com/rijum8906/relay/proto/pb/common/v1;commonv1\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1b\x06proto3"

var (
	file_common_v1_errors_proto_rawDescOnce sync.Once
	file_common_v1_errors_proto_rawDescData []byte
)

func file_common_v1_errors_proto_rawDescGZIP() []byte {
	file_common_v1_errors_proto_rawDescOnce.Do(func() {
		file_common_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)))
	})
	return file_common_v1_errors_proto_rawDescData
}

var file_common_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),          // 0: common.v1.ErrorCode
	(*ValidationError)(nil), // 1: common.v1.ValidationError
	(*ErrorDetails)(nil),    // 2: common.v1.ErrorDetails
	(*ErrorInfo)(nil),       // 3: common.v1.ErrorInfo
	(*ErrorResponse)(nil),   // 4: common.v1.ErrorResponse
	nil,                     // 5: common.v1.ErrorDetails.MetadataEntry
	nil,                     // 6: common.v1.ErrorInfo.MetadataEntry
}
var file_common_v1_errors_proto_depIdxs = []int32{
	0, // 0: common.v1.ErrorDetails.code:type_name -> common.v1.ErrorCode
	1, // 1: common.v1.ErrorDetails.validation_errors:type_name -> common.v1.ValidationError
	5, // 2: common.v1.ErrorDetails.metadata:type_name -> common.v1.ErrorDetails.MetadataEntry
	6, // 3: common.v1.ErrorInfo.metadata:type_name -> common.v1.ErrorInfo.MetadataEntry
	2, // 4: common.v1.ErrorResponse.error:type_name -> common.v1.ErrorDetails
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_v1_errors_proto_init() }
func file_common_v1_errors_proto_init() {
	if File_common_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_errors_proto_goTypes,
		DependencyIndexes: file_common_v1_errors_proto_depIdxs,
		EnumInfos:         file_common_v1_errors_proto_enumTypes,
		MessageInfos:      file_common_v1_errors_proto_msgTypes,
	}.Build()
	File_common_v1_errors_proto = out.File
	file_common_v1_errors_proto_goTypes = nil
	file_common_v1_errors_proto_depIdxs = nil
}
