// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/auth/v1/token.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateScopedTokenInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScopedTokenInput) Reset() {
	*x = GenerateScopedTokenInput{}
	mi := &file_user_auth_v1_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScopedTokenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScopedTokenInput) ProtoMessage() {}

func (x *GenerateScopedTokenInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_auth_v1_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScopedTokenInput.ProtoReflect.Descriptor instead.
func (*GenerateScopedTokenInput) Descriptor() ([]byte, []int) {
	return file_user_auth_v1_token_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateScopedTokenInput) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ChangePasswordInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordInput) Reset() {
	*x = ChangePasswordInput{}
	mi := &file_user_auth_v1_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordInput) ProtoMessage() {}

func (x *ChangePasswordInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_auth_v1_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordInput.ProtoReflect.Descriptor instead.
func (*ChangePasswordInput) Descriptor() ([]byte, []int) {
	return file_user_auth_v1_token_proto_rawDescGZIP(), []int{1}
}

func (x *ChangePasswordInput) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordInput) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RequestPasswordResetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetInput) Reset() {
	*x = RequestPasswordResetInput{}
	mi := &file_user_auth_v1_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetInput) ProtoMessage() {}

func (x *RequestPasswordResetInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_auth_v1_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetInput.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetInput) Descriptor() ([]byte, []int) {
	return file_user_auth_v1_token_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPasswordResetInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordInput) Reset() {
	*x = ResetPasswordInput{}
	mi := &file_user_auth_v1_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordInput) ProtoMessage() {}

func (x *ResetPasswordInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_auth_v1_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordInput.ProtoReflect.Descriptor instead.
func (*ResetPasswordInput) Descriptor() ([]byte, []int) {
	return file_user_auth_v1_token_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPasswordInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetPasswordInput) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type RequestEmailVerificationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationInput) Reset() {
	*x = RequestEmailVerificationInput{}
	mi := &file_user_auth_v1_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationInput) ProtoMessage() {}

func (x *RequestEmailVerificationInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_auth_v1_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationInput.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationInput) Descriptor() ([]byte, []int) {
	return file_user_auth_v1_token_proto_rawDescGZIP(), []int{4}
}

func (x *RequestEmailVerificationInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyEmailInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailInput) Reset() {
	*x = VerifyEmailInput{}
	mi := &file_user_auth_v1_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailInput) ProtoMessage() {}

func (x *VerifyEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_auth_v1_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailInput.ProtoReflect.Descriptor instead.
func (*VerifyEmailInput) Descriptor() ([]byte, []int) {
	return file_user_auth_v1_token_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyEmailInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_user_auth_v1_token_proto protoreflect.FileDescriptor

const file_user_auth_v1_token_proto_rawDesc = "" +
	"\n" +
	"\x18user/auth/v1/token.proto\x12\fuser.auth.v1\"0\n" +
	"\x18GenerateScopedTokenInput\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"c\n" +
	"\x13ChangePasswordInput\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"1\n" +
	"\x19RequestPasswordResetInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"M\n" +
	"\x12ResetPasswordInput\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"5\n" +
	"\x1dRequestEmailVerificationInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"(\n" +
	"\x10VerifyEmailInput\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05tokenB\xac\x01\n" +
	"\x10com.user.auth.v1B\n" +
	"TokenProtoP\x01Z:github.com/rijum8906/relay/packages/pb/user/auth/v1;authv1\xa2\x02\x03UAX\xaa\x02\fUser.Auth.V1\xca\x02\fUser\\Auth\\V1\xe2\x02\x18User\\Auth\\V1\\GPBMetadata\xea\x02\x0eUser::Auth::V1b\x06proto3"

var (
	file_user_auth_v1_token_proto_rawDescOnce sync.Once
	file_user_auth_v1_token_proto_rawDescData []byte
)

func file_user_auth_v1_token_proto_rawDescGZIP() []byte {
	file_user_auth_v1_token_proto_rawDescOnce.Do(func() {
		file_user_auth_v1_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_auth_v1_token_proto_rawDesc), len(file_user_auth_v1_token_proto_rawDesc)))
	})
	return file_user_auth_v1_token_proto_rawDescData
}

var file_user_auth_v1_token_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_auth_v1_token_proto_goTypes = []any{
	(*GenerateScopedTokenInput)(nil),      // 0: user.auth.v1.GenerateScopedTokenInput
	(*ChangePasswordInput)(nil),           // 1: user.auth.v1.ChangePasswordInput
	(*RequestPasswordResetInput)(nil),     // 2: user.auth.v1.RequestPasswordResetInput
	(*ResetPasswordInput)(nil),            // 3: user.auth.v1.ResetPasswordInput
	(*RequestEmailVerificationInput)(nil), // 4: user.auth.v1.RequestEmailVerificationInput
	(*VerifyEmailInput)(nil),              // 5: user.auth.v1.VerifyEmailInput
}
var file_user_auth_v1_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_auth_v1_token_proto_init() }
func file_user_auth_v1_token_proto_init() {
	if File_user_auth_v1_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_auth_v1_token_proto_rawDesc), len(file_user_auth_v1_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_auth_v1_token_proto_goTypes,
		DependencyIndexes: file_user_auth_v1_token_proto_depIdxs,
		MessageInfos:      file_user_auth_v1_token_proto_msgTypes,
	}.Build()
	File_user_auth_v1_token_proto = out.File
	file_user_auth_v1_token_proto_goTypes = nil
	file_user_auth_v1_token_proto_depIdxs = nil
}
