apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: relay
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: relay
type: Opaque
stringData:
  REDIS_PASSWORD:

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: relay
type: Opaque
stringData:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: password123

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: relay
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: supersecret
---
