apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: go-micro-service
data:
  APP_NAME: "user-service"
  APP_ENV: "production"
  APP_PORT: "8906"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  DB_SSL_MODE: "false"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_USER: ""
  REDIS_DB: "0"
  JWT_ISSUER: "user-service"
  JWT_EXPIRATION: "15m"
  SCOPED_JWT_EXPIRATION: "15m"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_FROM: "no-reply@yourdomain.com"
  OTP_EXPIRATION: "10m"
  BCRYPT_COST: "12"
  STORAGE_ENDPOINT: "http://minio:9000"
  STORAGE_BUCKET: "avatars"
  STORAGE_PUBLIC_KEY: "http://localhost:9000"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization,Content-Length"
  DEBUG: "false"
  LOG_LEVEL: "production"
