package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	user_servicev1 "github.com/rijum8906/relay/packages/pb/user_service/v1"
	"github.com/rijum8906/relay/services/graphql-gateway/graph/model"
	"github.com/rijum8906/relay/services/graphql-gateway/internal/utils"
)

// GenerateScopedToken is the resolver for the generateScopedToken field.
func (r *mutationResolver) GenerateScopedToken(ctx context.Context, input model.GenerateScopedTokenInput) (*model.Token, error) {
	resp, err := r.UserClient.GenerateScopedToken(withAuthzMetadata(ctx), &user_servicev1.GenerateScopedTokenRequest{
		Scope:    scopedActionToProto(input.Scope),
		AuthType: authTypeToProto(input.AuthType),
		Auth:     utils.NewString(input.Auth),
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapToken(resp.GetToken()), nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (*model.Response, error) {
	resp, err := r.UserClient.ChangePassword(withAuthzMetadata(ctx), &user_servicev1.ChangePasswordRequest{
		Token:       utils.NewString(input.Token),
		NewPassword: utils.NewPassword(input.NewPassword),
		Metadata:    requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, input model.DeleteAccountInput) (*model.Response, error) {
	resp, err := r.UserClient.DeleteAccount(withAuthzMetadata(ctx), &user_servicev1.DeleteAccountRequest{
		Token:    utils.NewString(input.Token),
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignupInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Signup(ctx, &user_servicev1.SignupRequest{
		Email:     utils.NewEmail(input.Email),
		Password:  utils.NewPassword(input.Password),
		FirstName: utils.NewName(input.FirstName),
		LastName:  utils.NewName(input.LastName),
		Metadata:  requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapAuthPayload(resp), nil
}

// Signin is the resolver for the signin field.
func (r *mutationResolver) Signin(ctx context.Context, input model.SigninInput) (*model.AuthPayload, error) {
	resp, err := r.UserClient.Signin(ctx, &user_servicev1.SigninRequest{
		Email:    utils.NewEmail(input.Email),
		Password: utils.NewPassword(input.Password),
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapAuthPayload(resp), nil
}

// Signout is the resolver for the signout field.
func (r *mutationResolver) Signout(ctx context.Context, input model.SignoutInput) (*model.Response, error) {
	resp, err := r.UserClient.Signout(withAuthzMetadata(ctx), &user_servicev1.SignoutRequest{
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input model.RequestPasswordResetInput) (*model.Response, error) {
	resp, err := r.UserClient.RequestPasswordReset(ctx, &user_servicev1.RequestPasswordResetRequest{
		Email:    utils.NewEmail(input.Email),
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPasswordInput) (*model.Response, error) {
	resp, err := r.UserClient.ResetPassword(ctx, &user_servicev1.ResetPasswordRequest{
		Token:       utils.NewToken(input.Token, 0),
		NewPassword: utils.NewPassword(input.NewPassword),
		Metadata:    requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}

// RequestEmailVerification is the resolver for the requestEmailVerification field.
func (r *mutationResolver) RequestEmailVerification(ctx context.Context, input model.RequestEmailVerificationInput) (*model.Response, error) {
	resp, err := r.UserClient.RequestEmailVerfication(withAuthzMetadata(ctx), &user_servicev1.RequestEmailVerificationRequest{
		Email:    utils.NewEmail(input.Email),
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input model.VerifyEmailInput) (*model.Response, error) {
	resp, err := r.UserClient.VerifyEmail(ctx, &user_servicev1.VerifyEmailRequest{
		Token:    utils.NewToken(input.Token, 0),
		Metadata: requestMetadataFromContext(ctx, input.Metadata),
	})
	if err != nil {
		return nil, err
	}

	return utils.MapResponse(resp.GetSuccess()), nil
}
