package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/rijum8906/relay/packages/core/apperror"
	"github.com/rijum8906/relay/packages/core/metadata"
	corev1 "github.com/rijum8906/relay/packages/pb/core/v1"
	taskv1 "github.com/rijum8906/relay/packages/pb/task_service/task/v1"
	authv1 "github.com/rijum8906/relay/packages/pb/user_service/auth/v1"
	sessionv1 "github.com/rijum8906/relay/packages/pb/user_service/session/v1"
	userv1 "github.com/rijum8906/relay/packages/pb/user_service/user/v1"
	"github.com/rijum8906/relay/services/graphql-gateway/graph/model"
	taskdto "github.com/rijum8906/relay/services/graphql-gateway/internal/dto/taskdto/task"
	userdto "github.com/rijum8906/relay/services/graphql-gateway/internal/dto/userdto/auth"
	"github.com/rijum8906/relay/services/graphql-gateway/internal/utils"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input userdto.LoginInput) (*model.AuthResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := attachClientMeta(ctx, input.Meta)
	if appErr != nil {
		return nil, appErr
	}

	resp, err := r.Clients.AuthClient.Login(ctx, &authv1.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}

	return utils.MapAuthResponse(resp.User, resp.Profile, resp.Tokens), nil
}

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input userdto.RegisterInput) (*model.AuthResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := attachClientMeta(ctx, input.Meta)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.AuthClient.Register(ctx, &authv1.RegisterRequest{
		Email:     input.Email,
		Password:  input.Password,
		FirstName: input.FirstName,
		LastName:  input.LastName,
	})
	if err != nil {
		return nil, err
	}

	return utils.MapAuthResponse(res.User, res.Profile, res.Tokens), nil
}

// LoginWithTwoFactorCode is the resolver for the LoginWithTwoFactorCode field.
func (r *mutationResolver) LoginWithTwoFactorCode(ctx context.Context, input model.TwoFactorCode) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: LoginWithTwoFactorCode - LoginWithTwoFactorCode"))
}

// Logout is the resolver for the Logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.MutationResponse, error) {
	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	tokens, ok := metadata.GetAuthTokensInfoFromIncomingContext(ctx)
	if !ok {
		return nil, apperror.ErrInternal.WithMessage("Failed to get auth tokens info from context")
	}

	res, err := r.Clients.AuthClient.Logout(ctx, &authv1.LogoutRequest{
		RefreshToken: tokens.RefreshToken,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}
	if !res.Success {
		return nil, apperror.ErrInternal.WithMessage("failed to logout")
	}

	return &model.MutationResponse{
		Success: res.Success,
	}, nil
}

// LogoutALlDevices is the resolver for the LogoutALlDevices field.
func (r *mutationResolver) LogoutALlDevices(ctx context.Context) (*model.MutationResponse, error) {
	panic(fmt.Errorf("not implemented: LogoutALlDevices - LogoutALlDevices"))
}

// RequestPasswordReset is the resolver for the RequestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, input userdto.RequestPasswordResetInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := attachClientMeta(ctx, input.Meta)
	if appErr != nil {
		return nil, appErr
	}

	resp, err := r.Clients.AuthClient.RequestPasswordReset(ctx, &authv1.RequestPasswordResetRequest{
		Email: input.Email,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return &model.MutationResponse{
		Success: resp.Success,
	}, nil
}

// ResetPassword is the resolver for the ResetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input userdto.ResetPasswordInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	resp, err := r.Clients.AuthClient.ResetPassword(ctx, &authv1.ResetPasswordRequest{
		ScopedToken: input.Token,
		NewPassword: input.NewPassword,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return &model.MutationResponse{
		Success: resp.Success,
	}, nil
}

// RequestEmailVerification is the resolver for the RequestEmailVerification field.
func (r *mutationResolver) RequestEmailVerification(ctx context.Context, input userdto.RequestEmailVerificationInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	resp, err := r.Clients.AuthClient.RequestEmailVerification(ctx, &authv1.RequestEmailVerificationRequest{
		Email: input.Email,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return &model.MutationResponse{
		Success: resp.Success,
	}, nil
}

// VerifyEmail is the resolver for the VerifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input userdto.VerifyEmailInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	resp, err := r.Clients.AuthClient.VerifyEmail(ctx, &authv1.VerifyEmailRequest{
		ScopedToken: input.Token,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return &model.MutationResponse{
		Success: resp.Success,
	}, nil
}

// GenerateScopedToken is the resolver for the GenerateScopedToken field.
func (r *mutationResolver) GenerateScopedToken(ctx context.Context, input userdto.GenerateScopedTokenInput) (*model.GenerateScopedTokenResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	authMethod, tokenScope, appErr := parseScopedToken(input.AuthMethod, input.Scope)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.AuthClient.GenerateScopedToken(ctx, &authv1.GenerateScopedTokenRequest{
		AuthMethod: authMethod.String(),
		Scope:      tokenScope.String(),
		AuthValue:  input.AuthValue,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return &model.GenerateScopedTokenResponse{
		ScopedToken: res.GetScopedToken(),
	}, nil
}

// RefershToken is the resolver for the RefershToken field.
func (r *mutationResolver) RefershToken(ctx context.Context) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: RefershToken - RefershToken"))
}

// RevokeSession is the resolver for the RevokeSession field.
func (r *mutationResolver) RevokeSession(ctx context.Context, input *model.RevokeSessionInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.SessionClient.RevokeSession(ctx, &sessionv1.RevokeSessionRequest{
		TokenToRevoke: input.TokenToRevoke,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}
	if !res.Success {
		return nil, apperror.ErrInternal.WithMessage("failed to revoke session")
	}

	return &model.MutationResponse{
		Success: res.Success,
	}, nil
}

// RevokeAllSessions is the resolver for the RevokeAllSessions field.
func (r *mutationResolver) RevokeAllSessions(ctx context.Context, input model.ScopedTokenInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.SessionClient.RevokeAllSessions(ctx, &corev1.EmptyRequest{})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}
	if !res.Success {
		return nil, apperror.ErrInternal.WithMessage("failed to revoke sessions")
	}

	return &model.MutationResponse{
		Success: res.Success,
	}, nil
}

// RevokeOthersSession is the resolver for the RevokeOthersSession field.
func (r *mutationResolver) RevokeOthersSession(ctx context.Context, input model.RevokeOthersSessionInput) (*model.AuthResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.SessionClient.RevokeOtherSessions(ctx, &sessionv1.RevokeOtherSessionsRequest{
		ScopedToken:      input.ScopedToken,
		CurrentSessionId: input.Token,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}
	// if !res.Success {
	// 	return nil, apperror.ErrInternal.WithMessage("failed to revoke other sessions")
	// }

	return &model.AuthResponse{
		Tokens: &model.AuthTokens{
			AccessToken: &model.Token{
				Value:     res.AccessToken.Value,
				ExpiresAt: res.AccessToken.ExpiresAt.String(),
			},
			RefreshToken: &model.Token{
				Value:     res.RefreshToken.Value,
				ExpiresAt: res.RefreshToken.ExpiresAt.String(),
			},
		},
	}, nil
}

// UpdateProfileAvatarURL is the resolver for the UpdateProfileAvatarUrl field.
func (r *mutationResolver) UpdateProfileAvatarURL(ctx context.Context, input userdto.UpdateProfileAvatarUrlInput) (*model.Profile, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.UserClient.UpdateProfileAvatarURL(ctx, &userv1.UpdateProfileAvatarURLRequest{
		ProfileId: input.ProfileID,
		AvatarUrl: input.AvatarURL,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return utils.MapProfile(res), nil
}

// UpdateProfileName is the resolver for the UpdateProfileName field.
func (r *mutationResolver) UpdateProfileName(ctx context.Context, input userdto.UpdateProfileNameInput) (*model.Profile, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.UserClient.UpdateProfileName(ctx, &userv1.UpdateProfileNameRequest{
		ProfileId: input.ProfileID,
		FirstName: input.FirstName,
		LastName:  input.LastName,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return utils.MapProfile(res), nil
}

// ChangePassword is the resolver for the ChangePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input userdto.ChangePasswordInput) (*model.MutationResponse, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.AuthClient.ChangePassword(ctx, &authv1.ChangePasswordRequest{
		ScopedToken: input.Token,
		NewPassword: input.NewPassword,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}
	if !res.Success {
		return nil, apperror.ErrInternal.WithMessage("failed to change password")
	}

	return &model.MutationResponse{Success: res.Success, Message: "password updated"}, nil
}

// CreateTask is the resolver for the CreateTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input taskdto.CreateTaskInput) (*model.Task, error) {
	if err := r.Validate.Struct(input); err != nil {
		return nil, apperror.ErrValidation.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	ctx, appErr := validateAndAttachUserInfo(ctx, r.TokenManager)
	if appErr != nil {
		return nil, appErr
	}

	dueAt, appErr := parseOptionalDateTime(input.DueAt, "dueAt")
	if appErr != nil {
		return nil, appErr
	}

	res, err := r.Clients.TaskClient.CreateTask(ctx, &taskv1.CreateTaskRequest{
		OrganizationId: stringValue(input.OrganizationID),
		ProjectId:      stringValue(input.ProjectID),
		ParentTaskId:   stringValue(input.ParentTaskID),
		Title:          input.Title,
		Description:    stringValue(input.Description),
		Priority:       stringValue(input.Priority),
		DueAt:          dueAt,
	})
	if err != nil {
		return nil, apperror.ErrThirdParty.WithMessage(err.Error()).WithDetail("error", err.Error())
	}

	return utils.MapTask(res), nil
}
