input LoginInput {
  email: String!
  password: String!
  meta: RequestMetaInput!
}

input RegisterInput {
  email: String!
  password: String!
  firstName: String!
  lastName: String!
  meta: RequestMetaInput!
}

input LogoutInput {
  meta: RequestMetaInput!
}

input RequestPasswordResetInput {
  email: String!
  meta: RequestMetaInput!
}

input ResetPasswordInput {
  token: String!
  newPassword: String!
}

input RequestEmailVerificationInput {
  email: String!
  meta: RequestMetaInput!
}

input  VerifyEmailInput {
  token: String!
  meta: RequestMetaInput!
}
