syntax = "proto3";

package user.auth.v1;

import "user/models/v1/model.proto";

message AuthResponse {
  user.models.v1.User user = 1;
  user.models.v1.Profile profile = 2;
  user.models.v1.AuthToken tokens = 3;
}

message GenerateScopedTokenResponse {
  user.models.v1.Token token = 1;
}

message ChangePasswordResponse {
  bool success = 1;
}

message RequestEmailVerificationResponse {
  bool success = 1;
}

message RequestPasswordResetResponse {
  bool success = 1;
}

message VerifyEmailResponse {
  bool success = 1;
}

message ResetPasswordResponse {
  bool success = 1;
}
