syntax = "proto3";

package user.auth.v1;

import "core/v1/common.proto";
import "user/auth/v1/profile.proto";
import "user/auth/v1/requst.proto";
import "user/auth/v1/response.proto";
import "user/auth/v1/token.proto";
import "user/models/v1/model.proto";

service AuthService {
  rpc Login(LoginRequest) returns (AuthResponse);
  rpc Register(RegisterRequest) returns (AuthResponse);
  rpc Logout(core.v1.EmptyRequest) returns (core.v1.SuccessResponse);
  rpc GenerateScopedToken(GenerateScopedTokenInput) returns (ScopedTokenResponse);
  rpc UpdateProfileAvatarUrl(UpdateProfileAvatarUrlInput) returns (user.models.v1.Profile);
  rpc UpdateProfileName(UpdateProfileNameInput) returns (user.models.v1.Profile);
  rpc ChangePassword(ChangePasswordInput) returns (MutationResponse);
  rpc RequestEmailVerification(core.v1.EmailInput) returns (core.v1.SuccessResponse);
  rpc RequestPasswordReset(core.v1.EmailInput) returns (core.v1.SuccessResponse);
  rpc VerifyEmail(VerifyEmailRequest) returns (core.v1.SuccessResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (core.v1.SuccessResponse);
}
