syntax = "proto3";

package user.auth.v1;

import "core/v1/common.proto";
import "user/auth/v1/requst.proto";
import "user/auth/v1/response.proto";

service AuthService {
  rpc Login(LoginRequest) returns (AuthResponse);
  rpc Register(RegisterRequest) returns (AuthResponse);
  rpc Logout(core.v1.EmptyRequest) returns (core.v1.SuccessResponse);
  rpc RequestEmailVerification(core.v1.EmailInput) returns (core.v1.SuccessResponse);
  rpc RequestPasswordReset(core.v1.EmailInput) returns (core.v1.SuccessResponse);
  rpc VerifyEmail(VerifyEmailRequest) returns (core.v1.SuccessResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (core.v1.SuccessResponse);
}
