// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    user_id,
    first_name,
    last_name,
    avatar_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, first_name, last_name, avatar_url, created_at, updated_at
`

type CreateProfileParams struct {
	UserID    uuid.UUID
	FirstName string
	LastName  string
	AvatarUrl string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, CreateProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteProfile, id)
	return err
}

const GetProfile = `-- name: GetProfile :one
SELECT id, user_id, first_name, last_name, avatar_url, created_at, updated_at
FROM profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, GetProfile, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, first_name, last_name, avatar_url, created_at, updated_at
FROM profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, GetProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET first_name = $2,
last_name = $3,
avatar_url = $4
WHERE id = $1
RETURNING id, user_id, first_name, last_name, avatar_url, created_at, updated_at
`

type UpdateProfileParams struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	AvatarUrl string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, UpdateProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
