set shell := ["zsh", "-c"]

# --- Build & Execution ---

# Build the service binary
build:
    @echo "Building web..."
    pnpm build

# Build and then run the binary
run: build
    @echo "Starting user-service..."

# Development run with hot reload 
dev:
    pnpm dev

# Setup
setup:
    pnpm i --frozen-lockfile

# Start local infrastructure (systemd)
infra:

# Stop core services [cite: 1]
infra-stop:
