// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/session/v1/request.proto

package sessionv1

import (
	v1 "github.com/rijum8906/relay/packages/pb/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetActiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSessionsRequest) Reset() {
	*x = GetActiveSessionsRequest{}
	mi := &file_user_service_session_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSessionsRequest) ProtoMessage() {}

func (x *GetActiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_session_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_session_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetActiveSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_user_service_session_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_session_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_session_v1_request_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSessionsRequest) GetPage() *v1.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopedToken   string                 `protobuf:"bytes,1,opt,name=scoped_token,json=scopedToken,proto3" json:"scoped_token,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_user_service_session_v1_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_session_v1_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_service_session_v1_request_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeSessionRequest) GetScopedToken() string {
	if x != nil {
		return x.ScopedToken
	}
	return ""
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_user_service_session_v1_request_proto protoreflect.FileDescriptor

const file_user_service_session_v1_request_proto_rawDesc = "" +
	"\n" +
	"%user_service/session/v1/request.proto\x12\x17user_service.session.v1\x1a\x14core/v1/common.proto\"3\n" +
	"\x18GetActiveSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x12GetSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.core.v1.PaginationRequestR\x04page\"X\n" +
	"\x14RevokeSessionRequest\x12!\n" +
	"\fscoped_token\x18\x01 \x01(\tR\vscopedToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionIdB\xef\x01\n" +
	"\x1bcom.user_service.session.v1B\fRequestProtoP\x01ZHgithub.com/rijum8906/relay/packages/pb/user_service/session/v1;sessionv1\xa2\x02\x03USX\xaa\x02\x16UserService.Session.V1\xca\x02\x16UserService\\Session\\V1\xe2\x02\"UserService\\Session\\V1\\GPBMetadata\xea\x02\x18UserService::Session::V1b\x06proto3"

var (
	file_user_service_session_v1_request_proto_rawDescOnce sync.Once
	file_user_service_session_v1_request_proto_rawDescData []byte
)

func file_user_service_session_v1_request_proto_rawDescGZIP() []byte {
	file_user_service_session_v1_request_proto_rawDescOnce.Do(func() {
		file_user_service_session_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_session_v1_request_proto_rawDesc), len(file_user_service_session_v1_request_proto_rawDesc)))
	})
	return file_user_service_session_v1_request_proto_rawDescData
}

var file_user_service_session_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_service_session_v1_request_proto_goTypes = []any{
	(*GetActiveSessionsRequest)(nil), // 0: user_service.session.v1.GetActiveSessionsRequest
	(*GetSessionsRequest)(nil),       // 1: user_service.session.v1.GetSessionsRequest
	(*RevokeSessionRequest)(nil),     // 2: user_service.session.v1.RevokeSessionRequest
	(*v1.PaginationRequest)(nil),     // 3: core.v1.PaginationRequest
}
var file_user_service_session_v1_request_proto_depIdxs = []int32{
	3, // 0: user_service.session.v1.GetSessionsRequest.page:type_name -> core.v1.PaginationRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_service_session_v1_request_proto_init() }
func file_user_service_session_v1_request_proto_init() {
	if File_user_service_session_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_session_v1_request_proto_rawDesc), len(file_user_service_session_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_session_v1_request_proto_goTypes,
		DependencyIndexes: file_user_service_session_v1_request_proto_depIdxs,
		MessageInfos:      file_user_service_session_v1_request_proto_msgTypes,
	}.Build()
	File_user_service_session_v1_request_proto = out.File
	file_user_service_session_v1_request_proto_goTypes = nil
	file_user_service_session_v1_request_proto_depIdxs = nil
}
