// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/session/v1/service.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_session_v1_service_proto protoreflect.FileDescriptor

const file_user_service_session_v1_service_proto_rawDesc = "" +
	"\n" +
	"%user_service/session/v1/service.proto\x12\x17user_service.session.v1\x1a%user_service/session/v1/request.proto\x1a&user_service/session/v1/response.proto2\xf6\x01\n" +
	"\x0eSessionService\x12h\n" +
	"\vGetSessions\x12+.user_service.session.v1.GetSessionsRequest\x1a,.user_service.session.v1.GetSessionsResponse\x12z\n" +
	"\x11GetActiveSessions\x121.user_service.session.v1.GetActiveSessionsRequest\x1a2.user_service.session.v1.GetActiveSessionsResponseB\xef\x01\n" +
	"\x1bcom.user_service.session.v1B\fServiceProtoP\x01ZHgithub.com/rijum8906/relay/packages/pb/user_service/session/v1;sessionv1\xa2\x02\x03USX\xaa\x02\x16UserService.Session.V1\xca\x02\x16UserService\\Session\\V1\xe2\x02\"UserService\\Session\\V1\\GPBMetadata\xea\x02\x18UserService::Session::V1b\x06proto3"

var file_user_service_session_v1_service_proto_goTypes = []any{
	(*GetSessionsRequest)(nil),        // 0: user_service.session.v1.GetSessionsRequest
	(*GetActiveSessionsRequest)(nil),  // 1: user_service.session.v1.GetActiveSessionsRequest
	(*GetSessionsResponse)(nil),       // 2: user_service.session.v1.GetSessionsResponse
	(*GetActiveSessionsResponse)(nil), // 3: user_service.session.v1.GetActiveSessionsResponse
}
var file_user_service_session_v1_service_proto_depIdxs = []int32{
	0, // 0: user_service.session.v1.SessionService.GetSessions:input_type -> user_service.session.v1.GetSessionsRequest
	1, // 1: user_service.session.v1.SessionService.GetActiveSessions:input_type -> user_service.session.v1.GetActiveSessionsRequest
	2, // 2: user_service.session.v1.SessionService.GetSessions:output_type -> user_service.session.v1.GetSessionsResponse
	3, // 3: user_service.session.v1.SessionService.GetActiveSessions:output_type -> user_service.session.v1.GetActiveSessionsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_session_v1_service_proto_init() }
func file_user_service_session_v1_service_proto_init() {
	if File_user_service_session_v1_service_proto != nil {
		return
	}
	file_user_service_session_v1_request_proto_init()
	file_user_service_session_v1_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_session_v1_service_proto_rawDesc), len(file_user_service_session_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_session_v1_service_proto_goTypes,
		DependencyIndexes: file_user_service_session_v1_service_proto_depIdxs,
	}.Build()
	File_user_service_session_v1_service_proto = out.File
	file_user_service_session_v1_service_proto_goTypes = nil
	file_user_service_session_v1_service_proto_depIdxs = nil
}
