// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CrateNotification = `-- name: CrateNotification :one
INSERT INTO notifications (
    recepient_email,
    recepient_user_id,
    message_data,
    status,
    template_type,
    retry_count
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, recepient_email, recepient_user_id, message_data, status, template_type, retry_count, last_error, created_at, updated_at
`

type CrateNotificationParams struct {
	RecepientEmail  string
	RecepientUserID uuid.UUID
	MessageData     []byte
	Status          string
	TemplateType    string
	RetryCount      int32
}

func (q *Queries) CrateNotification(ctx context.Context, arg CrateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, CrateNotification,
		arg.RecepientEmail,
		arg.RecepientUserID,
		arg.MessageData,
		arg.Status,
		arg.TemplateType,
		arg.RetryCount,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecepientEmail,
		&i.RecepientUserID,
		&i.MessageData,
		&i.Status,
		&i.TemplateType,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteNotification, id)
	return err
}

const DeleteNotificationsByStatus = `-- name: DeleteNotificationsByStatus :exec
DELETE FROM notifications
WHERE status = $1
`

func (q *Queries) DeleteNotificationsByStatus(ctx context.Context, status string) error {
	_, err := q.db.Exec(ctx, DeleteNotificationsByStatus, status)
	return err
}

const DeleteNotificationsByUserID = `-- name: DeleteNotificationsByUserID :exec
DELETE FROM notifications
WHERE recepient_user_id = $1
`

func (q *Queries) DeleteNotificationsByUserID(ctx context.Context, recepientUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteNotificationsByUserID, recepientUserID)
	return err
}

const GetNotification = `-- name: GetNotification :one
SELECT id, recepient_email, recepient_user_id, message_data, status, template_type, retry_count, last_error, created_at, updated_at
FROM notifications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, GetNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecepientEmail,
		&i.RecepientUserID,
		&i.MessageData,
		&i.Status,
		&i.TemplateType,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetNotifications = `-- name: GetNotifications :many
SELECT id, recepient_email, recepient_user_id, message_data, status, template_type, retry_count, last_error, created_at, updated_at
FROM notifications
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetNotificationsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, GetNotifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecepientEmail,
			&i.RecepientUserID,
			&i.MessageData,
			&i.Status,
			&i.TemplateType,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotificationsByStatus = `-- name: GetNotificationsByStatus :many

SELECT id, recepient_email, recepient_user_id, message_data, status, template_type, retry_count, last_error, created_at, updated_at
FROM notifications
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

// NOTE: these are not for user case
func (q *Queries) GetNotificationsByStatus(ctx context.Context, arg GetNotificationsByStatusParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, GetNotificationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecepientEmail,
			&i.RecepientUserID,
			&i.MessageData,
			&i.Status,
			&i.TemplateType,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotificationsByUserID = `-- name: GetNotificationsByUserID :many
SELECT id, recepient_email, recepient_user_id, message_data, status, template_type, retry_count, last_error, created_at, updated_at
FROM notifications
WHERE recepient_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByUserIDParams struct {
	RecepientUserID uuid.UUID
	Limit           int32
	Offset          int32
}

func (q *Queries) GetNotificationsByUserID(ctx context.Context, arg GetNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, GetNotificationsByUserID, arg.RecepientUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecepientEmail,
			&i.RecepientUserID,
			&i.MessageData,
			&i.Status,
			&i.TemplateType,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotificationsByUserIDAndStatus = `-- name: GetNotificationsByUserIDAndStatus :many
SELECT id, recepient_email, recepient_user_id, message_data, status, template_type, retry_count, last_error, created_at, updated_at
FROM notifications
WHERE status = $2 AND recepient_user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetNotificationsByUserIDAndStatusParams struct {
	RecepientUserID uuid.UUID
	Status          string
	Limit           int32
	Offset          int32
}

func (q *Queries) GetNotificationsByUserIDAndStatus(ctx context.Context, arg GetNotificationsByUserIDAndStatusParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, GetNotificationsByUserIDAndStatus,
		arg.RecepientUserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecepientEmail,
			&i.RecepientUserID,
			&i.MessageData,
			&i.Status,
			&i.TemplateType,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET status = $2
WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateNotificationStatus, arg.ID, arg.Status)
	return err
}
