// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteNotificationsByStatus(ctx context.Context, status string) error
	DeleteNotificationsByUserID(ctx context.Context, recepientUserID uuid.UUID) error
	GetNotification(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error)
	// NOTE: these are not for user case
	GetNotificationsByStatus(ctx context.Context, arg GetNotificationsByStatusParams) ([]Notification, error)
	GetNotificationsByUserID(ctx context.Context, arg GetNotificationsByUserIDParams) ([]Notification, error)
	GetNotificationsByUserIDAndStatus(ctx context.Context, arg GetNotificationsByUserIDAndStatusParams) ([]Notification, error)
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
}

var _ Querier = (*Queries)(nil)
