// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/v1/common.proto

package user_servicev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_user_service_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_user_service_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Name) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_user_service_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_user_service_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Email) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Password struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Password) Reset() {
	*x = Password{}
	mi := &file_user_service_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_user_service_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Password) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_user_service_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_user_service_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_user_service_v1_common_proto protoreflect.FileDescriptor

const file_user_service_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cuser_service/v1/common.proto\x12\x0fuser_service.v1\x1a\x1bbuf/validate/validate.proto\"'\n" +
	"\x04Name\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x05value\"(\n" +
	"\x05Email\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01`\x01R\x05value\"+\n" +
	"\bPassword\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\b\x182R\x05value\"#\n" +
	"\x02Id\x12\x1d\n" +
	"\x05value\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05valueB\xc2\x01\n" +
	"\x13com.user_service.v1B\vCommonProtoP\x01ZEgithub.com/rijum8906/relay/packages/pb/user_service/v1;user_servicev1\xa2\x02\x03UXX\xaa\x02\x0eUserService.V1\xca\x02\x0eUserService\\V1\xe2\x02\x1aUserService\\V1\\GPBMetadata\xea\x02\x0fUserService::V1b\x06proto3"

var (
	file_user_service_v1_common_proto_rawDescOnce sync.Once
	file_user_service_v1_common_proto_rawDescData []byte
)

func file_user_service_v1_common_proto_rawDescGZIP() []byte {
	file_user_service_v1_common_proto_rawDescOnce.Do(func() {
		file_user_service_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_v1_common_proto_rawDesc), len(file_user_service_v1_common_proto_rawDesc)))
	})
	return file_user_service_v1_common_proto_rawDescData
}

var (
	file_user_service_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
	file_user_service_v1_common_proto_goTypes  = []any{
		(*Name)(nil),     // 0: user_service.v1.Name
		(*Email)(nil),    // 1: user_service.v1.Email
		(*Password)(nil), // 2: user_service.v1.Password
		(*Id)(nil),       // 3: user_service.v1.Id
	}
)

var file_user_service_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_v1_common_proto_init() }
func file_user_service_v1_common_proto_init() {
	if File_user_service_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_v1_common_proto_rawDesc), len(file_user_service_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_v1_common_proto_goTypes,
		DependencyIndexes: file_user_service_v1_common_proto_depIdxs,
		MessageInfos:      file_user_service_v1_common_proto_msgTypes,
	}.Build()
	File_user_service_v1_common_proto = out.File
	file_user_service_v1_common_proto_goTypes = nil
	file_user_service_v1_common_proto_depIdxs = nil
}
