// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ArchiveOrganization = `-- name: ArchiveOrganization :exec
UPDATE organizations
SET
    status = 'archived',
    archived_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND status = 'active'
`

func (q *Queries) ArchiveOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ArchiveOrganization, id)
	return err
}

const ChangeOrganizationOwnership = `-- name: ChangeOrganizationOwnership :exec
UPDATE organizations
SET
    created_by_user_id = $1,
    updated_at = NOW()
WHERE id = $2
  AND deleted_at IS NULL
`

type ChangeOrganizationOwnershipParams struct {
	CreatedBy uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ChangeOrganizationOwnership(ctx context.Context, arg ChangeOrganizationOwnershipParams) error {
	_, err := q.db.Exec(ctx, ChangeOrganizationOwnership, arg.CreatedBy, arg.ID)
	return err
}

const CheckOrganizationExists = `-- name: CheckOrganizationExists :one
SELECT EXISTS (
    SELECT 1 FROM organizations
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) CheckOrganizationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, CheckOrganizationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CheckOrganizationExistsBySlug = `-- name: CheckOrganizationExistsBySlug :one
SELECT EXISTS (
    SELECT 1 FROM organizations
    WHERE slug = $1
) AS exists
`

func (q *Queries) CheckOrganizationExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, CheckOrganizationExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CreateOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name,
    slug,
    description,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, slug, description, logo_url, status, created_by_user_id, created_at, updated_at, archived_at, deleted_at
`

type CreateOrganizationParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, CreateOrganization,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedBy,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const DeleteOrganization = `-- name: DeleteOrganization :exec
UPDATE organizations
SET
    status = 'deleted',
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganization, id)
	return err
}

const DeleteOrganizationHard = `-- name: DeleteOrganizationHard :exec
DELETE FROM organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganizationHard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganizationHard, id)
	return err
}

const GetDeletedOrganization = `-- name: GetDeletedOrganization :one
SELECT id, name, slug, description, logo_url, status, created_by_user_id, created_at, updated_at, archived_at, deleted_at FROM organizations
WHERE id = $1
  AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, GetDeletedOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, description, logo_url, status, created_by_user_id, created_at, updated_at, archived_at, deleted_at FROM organizations
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, GetOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, description, logo_url, status, created_by_user_id, created_at, updated_at, archived_at, deleted_at FROM organizations
WHERE slug = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, GetOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationsByCreatedBy = `-- name: GetOrganizationsByCreatedBy :many
SELECT id, name, slug, description, logo_url, status, created_by_user_id, created_at, updated_at, archived_at, deleted_at FROM organizations
WHERE created_by_user_id = $3
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetOrganizationsByCreatedByParams struct {
	Limit     int32
	Offset    int32
	CreatedBy uuid.UUID
}

func (q *Queries) GetOrganizationsByCreatedBy(ctx context.Context, arg GetOrganizationsByCreatedByParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, GetOrganizationsByCreatedBy, arg.Limit, arg.Offset, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.Status,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RestoreArchivedOrganization = `-- name: RestoreArchivedOrganization :exec
UPDATE organizations
SET
    status = 'active',
    archived_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND status = 'archived'
`

func (q *Queries) RestoreArchivedOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, RestoreArchivedOrganization, id)
	return err
}

const UpdateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    name = $2,
    description = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, description, logo_url, status, created_by_user_id, created_at, updated_at, archived_at, deleted_at
`

type UpdateOrganizationParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, UpdateOrganization, arg.ID, arg.Name, arg.Description)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.Status,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}
