// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ArchiveOrganizationTeam = `-- name: ArchiveOrganizationTeam :exec
UPDATE organization_teams
SET
    status = 'archived',
    archived_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND status = 'active'
`

func (q *Queries) ArchiveOrganizationTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ArchiveOrganizationTeam, id)
	return err
}

const CheckOrganizationTeamExists = `-- name: CheckOrganizationTeamExists :one
SELECT EXISTS (
    SELECT 1 FROM organization_teams
    WHERE id = $1
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) CheckOrganizationTeamExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, CheckOrganizationTeamExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CheckOrganizationTeamNameExists = `-- name: CheckOrganizationTeamNameExists :one
SELECT EXISTS (
    SELECT 1 FROM organization_teams
    WHERE organization_id = $1
      AND name = $2
      AND status IN ('active', 'archived')
) AS exists
`

type CheckOrganizationTeamNameExistsParams struct {
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) CheckOrganizationTeamNameExists(ctx context.Context, arg CheckOrganizationTeamNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, CheckOrganizationTeamNameExists, arg.OrganizationID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CountOrganizationTeamsByOrgID = `-- name: CountOrganizationTeamsByOrgID :one
SELECT COUNT(*) FROM organization_teams
WHERE organization_id = $1
  AND status = 'active'
`

func (q *Queries) CountOrganizationTeamsByOrgID(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountOrganizationTeamsByOrgID, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountOrganizationTeamsByOrgIDAndStatus = `-- name: CountOrganizationTeamsByOrgIDAndStatus :one
SELECT COUNT(*) FROM organization_teams
WHERE organization_id = $1
  AND status = $2
`

type CountOrganizationTeamsByOrgIDAndStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
}

func (q *Queries) CountOrganizationTeamsByOrgIDAndStatus(ctx context.Context, arg CountOrganizationTeamsByOrgIDAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountOrganizationTeamsByOrgIDAndStatus, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateOrganizationTeam = `-- name: CreateOrganizationTeam :one
INSERT INTO organization_teams (
    organization_id,
    name,
    description,
    created_by_mem_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at
`

type CreateOrganizationTeamParams struct {
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	CreatedByMemID uuid.UUID
}

func (q *Queries) CreateOrganizationTeam(ctx context.Context, arg CreateOrganizationTeamParams) (OrganizationTeam, error) {
	row := q.db.QueryRow(ctx, CreateOrganizationTeam,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.CreatedByMemID,
	)
	var i OrganizationTeam
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedByMemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const DeleteOrganizationTeam = `-- name: DeleteOrganizationTeam :exec
UPDATE organization_teams
SET
    status = 'deleted',
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteOrganizationTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganizationTeam, id)
	return err
}

const DeleteOrganizationTeamHard = `-- name: DeleteOrganizationTeamHard :exec
DELETE FROM organization_teams
WHERE id = $1
`

func (q *Queries) DeleteOrganizationTeamHard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganizationTeamHard, id)
	return err
}

const DeleteOrganizationTeamsByOrgIDHard = `-- name: DeleteOrganizationTeamsByOrgIDHard :exec
DELETE FROM organization_teams
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationTeamsByOrgIDHard(ctx context.Context, organizationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganizationTeamsByOrgIDHard, organizationID)
	return err
}

const GetDeletedOrganizationTeam = `-- name: GetDeletedOrganizationTeam :one
SELECT id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at FROM organization_teams
WHERE id = $1
  AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedOrganizationTeam(ctx context.Context, id uuid.UUID) (OrganizationTeam, error) {
	row := q.db.QueryRow(ctx, GetDeletedOrganizationTeam, id)
	var i OrganizationTeam
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedByMemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationTeam = `-- name: GetOrganizationTeam :one
SELECT id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at FROM organization_teams
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrganizationTeam(ctx context.Context, id uuid.UUID) (OrganizationTeam, error) {
	row := q.db.QueryRow(ctx, GetOrganizationTeam, id)
	var i OrganizationTeam
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedByMemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationTeamByOrgIDAndName = `-- name: GetOrganizationTeamByOrgIDAndName :one
SELECT id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at FROM organization_teams
WHERE organization_id = $1
  AND name = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetOrganizationTeamByOrgIDAndNameParams struct {
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) GetOrganizationTeamByOrgIDAndName(ctx context.Context, arg GetOrganizationTeamByOrgIDAndNameParams) (OrganizationTeam, error) {
	row := q.db.QueryRow(ctx, GetOrganizationTeamByOrgIDAndName, arg.OrganizationID, arg.Name)
	var i OrganizationTeam
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedByMemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}

const GetOrganizationTeamsByCreatedBy = `-- name: GetOrganizationTeamsByCreatedBy :many
SELECT id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at FROM organization_teams
WHERE created_by_mem_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrganizationTeamsByCreatedByParams struct {
	CreatedByMemID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetOrganizationTeamsByCreatedBy(ctx context.Context, arg GetOrganizationTeamsByCreatedByParams) ([]OrganizationTeam, error) {
	rows, err := q.db.Query(ctx, GetOrganizationTeamsByCreatedBy, arg.CreatedByMemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationTeam{}
	for rows.Next() {
		var i OrganizationTeam
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedByMemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrganizationTeamsByOrgID = `-- name: GetOrganizationTeamsByOrgID :many
SELECT id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at FROM organization_teams
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrganizationTeamsByOrgIDParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetOrganizationTeamsByOrgID(ctx context.Context, arg GetOrganizationTeamsByOrgIDParams) ([]OrganizationTeam, error) {
	rows, err := q.db.Query(ctx, GetOrganizationTeamsByOrgID, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationTeam{}
	for rows.Next() {
		var i OrganizationTeam
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedByMemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrganizationTeamsByOrgIDAndStatus = `-- name: GetOrganizationTeamsByOrgIDAndStatus :many
SELECT id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at FROM organization_teams
WHERE organization_id = $1
  AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetOrganizationTeamsByOrgIDAndStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

func (q *Queries) GetOrganizationTeamsByOrgIDAndStatus(ctx context.Context, arg GetOrganizationTeamsByOrgIDAndStatusParams) ([]OrganizationTeam, error) {
	rows, err := q.db.Query(ctx, GetOrganizationTeamsByOrgIDAndStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationTeam{}
	for rows.Next() {
		var i OrganizationTeam
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedByMemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RestoreArchivedOrganizationTeam = `-- name: RestoreArchivedOrganizationTeam :exec
UPDATE organization_teams
SET
    status = 'active',
    archived_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND status = 'archived'
`

func (q *Queries) RestoreArchivedOrganizationTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, RestoreArchivedOrganizationTeam, id)
	return err
}

const UpdateOrganizationTeam = `-- name: UpdateOrganizationTeam :one
UPDATE organization_teams
SET
    name = $2,
    description = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, organization_id, name, description, status, created_by_mem_id, created_at, updated_at, archived_at, deleted_at
`

type UpdateOrganizationTeamParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateOrganizationTeam(ctx context.Context, arg UpdateOrganizationTeamParams) (OrganizationTeam, error) {
	row := q.db.QueryRow(ctx, UpdateOrganizationTeam, arg.ID, arg.Name, arg.Description)
	var i OrganizationTeam
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedByMemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.DeletedAt,
	)
	return i, err
}
