// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgnization_invitations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AccecptOrganizationInvitation = `-- name: AccecptOrganizationInvitation :one
UPDATE organization_invitations
SET status = 'accepted', responded_by = $2, responded_at = now(), response = 'accept'
WHERE id = $1
RETURNING id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at
`

type AccecptOrganizationInvitationParams struct {
	ID          uuid.UUID
	RespondedBy uuid.UUID
}

func (q *Queries) AccecptOrganizationInvitation(ctx context.Context, arg AccecptOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, AccecptOrganizationInvitation, arg.ID, arg.RespondedBy)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedByMemID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.Response,
		&i.RevokedByMemID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const CheckOrganizationInvitationExists = `-- name: CheckOrganizationInvitationExists :one
SELECT EXISTS (
    SELECT 1 FROM organization_invitations
    WHERE id = $1
)
`

func (q *Queries) CheckOrganizationInvitationExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, CheckOrganizationInvitationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CheckOrganizationInvitationExistsByTokenHash = `-- name: CheckOrganizationInvitationExistsByTokenHash :one
SELECT EXISTS (
    SELECT 1 FROM organization_invitations
    WHERE token_hash = $1
)
`

func (q *Queries) CheckOrganizationInvitationExistsByTokenHash(ctx context.Context, tokenHash string) (bool, error) {
	row := q.db.QueryRow(ctx, CheckOrganizationInvitationExistsByTokenHash, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CreateOrganizationInvitation = `-- name: CreateOrganizationInvitation :one
INSERT INTO organization_invitations (
    organization_id, email, role, invited_by_mem_id, token_hash, expires_at
) VALUES ( $1, $2, $3, $4, $5, $6)
    RETURNING id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at
`

type CreateOrganizationInvitationParams struct {
	OrganizationID uuid.UUID
	Email          string
	Role           string
	InvitedByMemID uuid.UUID
	TokenHash      string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateOrganizationInvitation(ctx context.Context, arg CreateOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, CreateOrganizationInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.InvitedByMemID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedByMemID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.Response,
		&i.RevokedByMemID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const DeclineOrganizationInvitation = `-- name: DeclineOrganizationInvitation :one
UPDATE organization_invitations SET status = 'declined', responded_by = $2, responded_at = now(), response = 'decline'
WHERE id = $1
RETURNING id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at
`

type DeclineOrganizationInvitationParams struct {
	ID          uuid.UUID
	RespondedBy uuid.UUID
}

func (q *Queries) DeclineOrganizationInvitation(ctx context.Context, arg DeclineOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, DeclineOrganizationInvitation, arg.ID, arg.RespondedBy)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedByMemID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.Response,
		&i.RevokedByMemID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteOrganizationInvitation = `-- name: DeleteOrganizationInvitation :exec
DELETE FROM organization_invitations
WHERE id = $1
`

func (q *Queries) DeleteOrganizationInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganizationInvitation, id)
	return err
}

const GetOrganizationInvitation = `-- name: GetOrganizationInvitation :one
SELECT id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at FROM organization_invitations
WHERE id = $1
`

func (q *Queries) GetOrganizationInvitation(ctx context.Context, id uuid.UUID) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, GetOrganizationInvitation, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedByMemID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.Response,
		&i.RevokedByMemID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetOrganizationInvitationByTokenHash = `-- name: GetOrganizationInvitationByTokenHash :one
SELECT id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at FROM organization_invitations
WHERE token_hash = $1
`

func (q *Queries) GetOrganizationInvitationByTokenHash(ctx context.Context, tokenHash string) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, GetOrganizationInvitationByTokenHash, tokenHash)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedByMemID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.Response,
		&i.RevokedByMemID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetOrganizationInvitationsByOrgID = `-- name: GetOrganizationInvitationsByOrgID :many
SELECT id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at FROM organization_invitations
WHERE organization_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetOrganizationInvitationsByOrgIDParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetOrganizationInvitationsByOrgID(ctx context.Context, arg GetOrganizationInvitationsByOrgIDParams) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, GetOrganizationInvitationsByOrgID, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitation{}
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InvitedByMemID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.RespondedBy,
			&i.RespondedAt,
			&i.Response,
			&i.RevokedByMemID,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrganizationInvitationsByOrgIDAndStatus = `-- name: GetOrganizationInvitationsByOrgIDAndStatus :many
SELECT id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at FROM organization_invitations
WHERE organization_id = $1 AND status = $2
ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type GetOrganizationInvitationsByOrgIDAndStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

func (q *Queries) GetOrganizationInvitationsByOrgIDAndStatus(ctx context.Context, arg GetOrganizationInvitationsByOrgIDAndStatusParams) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, GetOrganizationInvitationsByOrgIDAndStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitation{}
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.InvitedByMemID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.RespondedBy,
			&i.RespondedAt,
			&i.Response,
			&i.RevokedByMemID,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeOrganizationInvitation = `-- name: RevokeOrganizationInvitation :one
UPDATE organization_invitations
SET status = 'revoked', revoked_by_mem_id = $2, revoked_at = now()
WHERE id = $1
RETURNING id, organization_id, email, role, status, invited_by_mem_id, token_hash, expires_at, responded_by, responded_at, response, revoked_by_mem_id, revoked_at, created_at
`

type RevokeOrganizationInvitationParams struct {
	ID             uuid.UUID
	RevokedByMemID uuid.UUID
}

func (q *Queries) RevokeOrganizationInvitation(ctx context.Context, arg RevokeOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, RevokeOrganizationInvitation, arg.ID, arg.RevokedByMemID)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.InvitedByMemID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RespondedBy,
		&i.RespondedAt,
		&i.Response,
		&i.RevokedByMemID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
