// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/user/v1/request.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateProfileAvatarURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileAvatarURLRequest) Reset() {
	*x = UpdateProfileAvatarURLRequest{}
	mi := &file_user_service_user_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileAvatarURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileAvatarURLRequest) ProtoMessage() {}

func (x *UpdateProfileAvatarURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileAvatarURLRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileAvatarURLRequest) Descriptor() ([]byte, []int) {
	return file_user_service_user_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateProfileAvatarURLRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UpdateProfileAvatarURLRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateProfileNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileNameRequest) Reset() {
	*x = UpdateProfileNameRequest{}
	mi := &file_user_service_user_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileNameRequest) ProtoMessage() {}

func (x *UpdateProfileNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileNameRequest) Descriptor() ([]byte, []int) {
	return file_user_service_user_v1_request_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileNameRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UpdateProfileNameRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileNameRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_user_service_user_v1_request_proto protoreflect.FileDescriptor

const file_user_service_user_v1_request_proto_rawDesc = "" +
	"\n" +
	"\"user_service/user/v1/request.proto\x12\x14user_service.user.v1\"]\n" +
	"\x1dUpdateProfileAvatarURLRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\"u\n" +
	"\x18UpdateProfileNameRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastNameB\xda\x01\n" +
	"\x18com.user_service.user.v1B\fRequestProtoP\x01ZBgithub.com/rijum8906/relay/packages/pb/user_service/user/v1;userv1\xa2\x02\x03UUX\xaa\x02\x13UserService.User.V1\xca\x02\x13UserService\\User\\V1\xe2\x02\x1fUserService\\User\\V1\\GPBMetadata\xea\x02\x15UserService::User::V1b\x06proto3"

var (
	file_user_service_user_v1_request_proto_rawDescOnce sync.Once
	file_user_service_user_v1_request_proto_rawDescData []byte
)

func file_user_service_user_v1_request_proto_rawDescGZIP() []byte {
	file_user_service_user_v1_request_proto_rawDescOnce.Do(func() {
		file_user_service_user_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_user_v1_request_proto_rawDesc), len(file_user_service_user_v1_request_proto_rawDesc)))
	})
	return file_user_service_user_v1_request_proto_rawDescData
}

var file_user_service_user_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_service_user_v1_request_proto_goTypes = []any{
	(*UpdateProfileAvatarURLRequest)(nil), // 0: user_service.user.v1.UpdateProfileAvatarURLRequest
	(*UpdateProfileNameRequest)(nil),      // 1: user_service.user.v1.UpdateProfileNameRequest
}
var file_user_service_user_v1_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_user_v1_request_proto_init() }
func file_user_service_user_v1_request_proto_init() {
	if File_user_service_user_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_user_v1_request_proto_rawDesc), len(file_user_service_user_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_user_v1_request_proto_goTypes,
		DependencyIndexes: file_user_service_user_v1_request_proto_depIdxs,
		MessageInfos:      file_user_service_user_v1_request_proto_msgTypes,
	}.Build()
	File_user_service_user_v1_request_proto = out.File
	file_user_service_user_v1_request_proto_goTypes = nil
	file_user_service_user_v1_request_proto_depIdxs = nil
}
