// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/user/v1/response.proto

package userv1

import (
	v1 "github.com/rijum8906/relay/packages/pb/user_service/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateScopedTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *v1.Token              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScopedTokenResponse) Reset() {
	*x = GenerateScopedTokenResponse{}
	mi := &file_user_service_user_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScopedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScopedTokenResponse) ProtoMessage() {}

func (x *GenerateScopedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScopedTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateScopedTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_service_user_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateScopedTokenResponse) GetToken() *v1.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_user_service_user_v1_response_proto protoreflect.FileDescriptor

const file_user_service_user_v1_response_proto_rawDesc = "" +
	"\n" +
	"#user_service/user/v1/response.proto\x12\x14user_service.user.v1\x1a\"user_service/models/v1/model.proto\"R\n" +
	"\x1bGenerateScopedTokenResponse\x123\n" +
	"\x05token\x18\x01 \x01(\v2\x1d.user_service.models.v1.TokenR\x05tokenB\xdb\x01\n" +
	"\x18com.user_service.user.v1B\rResponseProtoP\x01ZBgithub.com/rijum8906/relay/packages/pb/user_service/user/v1;userv1\xa2\x02\x03UUX\xaa\x02\x13UserService.User.V1\xca\x02\x13UserService\\User\\V1\xe2\x02\x1fUserService\\User\\V1\\GPBMetadata\xea\x02\x15UserService::User::V1b\x06proto3"

var (
	file_user_service_user_v1_response_proto_rawDescOnce sync.Once
	file_user_service_user_v1_response_proto_rawDescData []byte
)

func file_user_service_user_v1_response_proto_rawDescGZIP() []byte {
	file_user_service_user_v1_response_proto_rawDescOnce.Do(func() {
		file_user_service_user_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_user_v1_response_proto_rawDesc), len(file_user_service_user_v1_response_proto_rawDesc)))
	})
	return file_user_service_user_v1_response_proto_rawDescData
}

var file_user_service_user_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_service_user_v1_response_proto_goTypes = []any{
	(*GenerateScopedTokenResponse)(nil), // 0: user_service.user.v1.GenerateScopedTokenResponse
	(*v1.Token)(nil),                    // 1: user_service.models.v1.Token
}
var file_user_service_user_v1_response_proto_depIdxs = []int32{
	1, // 0: user_service.user.v1.GenerateScopedTokenResponse.token:type_name -> user_service.models.v1.Token
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_service_user_v1_response_proto_init() }
func file_user_service_user_v1_response_proto_init() {
	if File_user_service_user_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_user_v1_response_proto_rawDesc), len(file_user_service_user_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_user_v1_response_proto_goTypes,
		DependencyIndexes: file_user_service_user_v1_response_proto_depIdxs,
		MessageInfos:      file_user_service_user_v1_response_proto_msgTypes,
	}.Build()
	File_user_service_user_v1_response_proto = out.File
	file_user_service_user_v1_response_proto_goTypes = nil
	file_user_service_user_v1_response_proto_depIdxs = nil
}
