// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/profile/v1/messages.proto

package profilev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/rijum8906/relay/packages/pb/common/v1"
	v11 "github.com/rijum8906/relay/packages/pb/user_service/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     *v1.UUID               `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetProfileId() *v1.UUID {
	if x != nil {
		return x.ProfileId
	}
	return nil
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *v11.Profile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetProfile() *v11.Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetMyProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyProfilesRequest) Reset() {
	*x = GetMyProfilesRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyProfilesRequest) ProtoMessage() {}

func (x *GetMyProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetMyProfilesRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyProfilesRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *GetMyProfilesRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetMyProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*v11.Profile         `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyProfilesResponse) Reset() {
	*x = GetMyProfilesResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyProfilesResponse) ProtoMessage() {}

func (x *GetMyProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetMyProfilesResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyProfilesResponse) GetProfiles() []*v11.Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ProfileId     *v1.UUID               `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FirstName     *v1.Name               `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *v1.Name               `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DisplayName   *v1.Name               `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	AvatarUrl     *v1.Url                `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *UpdateProfileRequest) GetProfileId() *v1.UUID {
	if x != nil {
		return x.ProfileId
	}
	return nil
}

func (x *UpdateProfileRequest) GetFirstName() *v1.Name {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *UpdateProfileRequest) GetLastName() *v1.Name {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *UpdateProfileRequest) GetDisplayName() *v1.Name {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *UpdateProfileRequest) GetAvatarUrl() *v1.Url {
	if x != nil {
		return x.AvatarUrl
	}
	return nil
}

func (x *UpdateProfileRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *v11.Profile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileResponse) GetProfile() *v11.Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ProfileId     *v1.UUID               `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProfileRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *DeleteProfileRequest) GetProfileId() *v1.UUID {
	if x != nil {
		return x.ProfileId
	}
	return nil
}

func (x *DeleteProfileRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateDisplayNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ProfileId     *v1.UUID               `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DisplayName   *v1.Name               `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDisplayNameRequest) Reset() {
	*x = UpdateDisplayNameRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDisplayNameRequest) ProtoMessage() {}

func (x *UpdateDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDisplayNameRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *UpdateDisplayNameRequest) GetProfileId() *v1.UUID {
	if x != nil {
		return x.ProfileId
	}
	return nil
}

func (x *UpdateDisplayNameRequest) GetDisplayName() *v1.Name {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *UpdateDisplayNameRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateDisplayNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *v11.Profile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDisplayNameResponse) Reset() {
	*x = UpdateDisplayNameResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDisplayNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDisplayNameResponse) ProtoMessage() {}

func (x *UpdateDisplayNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDisplayNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateDisplayNameResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDisplayNameResponse) GetProfile() *v11.Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ProfileId     *v1.UUID               `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FirstName     *v1.Name               `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *v1.Name               `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNameRequest) Reset() {
	*x = UpdateNameRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameRequest) ProtoMessage() {}

func (x *UpdateNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateNameRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateNameRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *UpdateNameRequest) GetProfileId() *v1.UUID {
	if x != nil {
		return x.ProfileId
	}
	return nil
}

func (x *UpdateNameRequest) GetFirstName() *v1.Name {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *UpdateNameRequest) GetLastName() *v1.Name {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *UpdateNameRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *v11.Profile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNameResponse) Reset() {
	*x = UpdateNameResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameResponse) ProtoMessage() {}

func (x *UpdateNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateNameResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNameResponse) GetProfile() *v11.Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateAvatarUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *v1.Token              `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ProfileId     *v1.UUID               `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	AvatarUrl     *v1.Url                `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Metadata      *v1.RequestMetadata    `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarUrlRequest) Reset() {
	*x = UpdateAvatarUrlRequest{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarUrlRequest) ProtoMessage() {}

func (x *UpdateAvatarUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarUrlRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarUrlRequest) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateAvatarUrlRequest) GetAccessToken() *v1.Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *UpdateAvatarUrlRequest) GetProfileId() *v1.UUID {
	if x != nil {
		return x.ProfileId
	}
	return nil
}

func (x *UpdateAvatarUrlRequest) GetAvatarUrl() *v1.Url {
	if x != nil {
		return x.AvatarUrl
	}
	return nil
}

func (x *UpdateAvatarUrlRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateAvatarUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *v11.Profile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarUrlResponse) Reset() {
	*x = UpdateAvatarUrlResponse{}
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarUrlResponse) ProtoMessage() {}

func (x *UpdateAvatarUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_profile_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarUrlResponse.ProtoReflect.Descriptor instead.
func (*UpdateAvatarUrlResponse) Descriptor() ([]byte, []int) {
	return file_user_service_profile_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAvatarUrlResponse) GetProfile() *v11.Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_user_service_profile_v1_messages_proto protoreflect.FileDescriptor

const file_user_service_profile_v1_messages_proto_rawDesc = "" +
	"\n" +
	"&user_service/profile/v1/messages.proto\x12\x17user_service.profile.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x1cuser_service/v1/models.proto\"K\n" +
	"\x11GetProfileRequest\x126\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tprofileId\"P\n" +
	"\x12GetProfileResponse\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.user_service.v1.ProfileB\x06\xbaH\x03\xc8\x01\x01R\aprofile\"\x93\x01\n" +
	"\x14GetMyProfilesRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"M\n" +
	"\x15GetMyProfilesResponse\x124\n" +
	"\bprofiles\x18\x01 \x03(\v2\x18.user_service.v1.ProfileR\bprofiles\"\xc6\x03\n" +
	"\x14UpdateProfileRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x126\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tprofileId\x126\n" +
	"\n" +
	"first_name\x18\x03 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\tfirstName\x124\n" +
	"\tlast_name\x18\x04 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\blastName\x127\n" +
	"\fdisplay_name\x18\x05 \x01(\v2\x0f.common.v1.NameH\x00R\vdisplayName\x88\x01\x01\x122\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\v2\x0e.common.v1.UrlH\x01R\tavatarUrl\x88\x01\x01\x12>\n" +
	"\bmetadata\x18\a \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadataB\x0f\n" +
	"\r_display_nameB\r\n" +
	"\v_avatar_url\"S\n" +
	"\x15UpdateProfileResponse\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.user_service.v1.ProfileB\x06\xbaH\x03\xc8\x01\x01R\aprofile\"\xcb\x01\n" +
	"\x14DeleteProfileRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x126\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tprofileId\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"1\n" +
	"\x15DeleteProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8b\x02\n" +
	"\x18UpdateDisplayNameRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x126\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tprofileId\x12:\n" +
	"\fdisplay_name\x18\x03 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\vdisplayName\x12>\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"W\n" +
	"\x19UpdateDisplayNameResponse\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.user_service.v1.ProfileB\x06\xbaH\x03\xc8\x01\x01R\aprofile\"\xb6\x02\n" +
	"\x11UpdateNameRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x126\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tprofileId\x126\n" +
	"\n" +
	"first_name\x18\x03 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\tfirstName\x124\n" +
	"\tlast_name\x18\x04 \x01(\v2\x0f.common.v1.NameB\x06\xbaH\x03\xc8\x01\x01R\blastName\x12>\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"P\n" +
	"\x12UpdateNameResponse\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.user_service.v1.ProfileB\x06\xbaH\x03\xc8\x01\x01R\aprofile\"\x84\x02\n" +
	"\x16UpdateAvatarUrlRequest\x12;\n" +
	"\faccess_token\x18\x01 \x01(\v2\x10.common.v1.TokenB\x06\xbaH\x03\xc8\x01\x01R\vaccessToken\x126\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\v2\x0f.common.v1.UUIDB\x06\xbaH\x03\xc8\x01\x01R\tprofileId\x125\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\v2\x0e.common.v1.UrlB\x06\xbaH\x03\xc8\x01\x01R\tavatarUrl\x12>\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1a.common.v1.RequestMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\"U\n" +
	"\x17UpdateAvatarUrlResponse\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.user_service.v1.ProfileB\x06\xbaH\x03\xc8\x01\x01R\aprofileB\xf0\x01\n" +
	"\x1bcom.user_service.profile.v1B\rMessagesProtoP\x01ZHgithub.com/rijum8906/relay/packages/pb/user_service/profile/v1;profilev1\xa2\x02\x03UPX\xaa\x02\x16UserService.Profile.V1\xca\x02\x16UserService\\Profile\\V1\xe2\x02\"UserService\\Profile\\V1\\GPBMetadata\xea\x02\x18UserService::Profile::V1b\x06proto3"

var (
	file_user_service_profile_v1_messages_proto_rawDescOnce sync.Once
	file_user_service_profile_v1_messages_proto_rawDescData []byte
)

func file_user_service_profile_v1_messages_proto_rawDescGZIP() []byte {
	file_user_service_profile_v1_messages_proto_rawDescOnce.Do(func() {
		file_user_service_profile_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_profile_v1_messages_proto_rawDesc), len(file_user_service_profile_v1_messages_proto_rawDesc)))
	})
	return file_user_service_profile_v1_messages_proto_rawDescData
}

var file_user_service_profile_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_service_profile_v1_messages_proto_goTypes = []any{
	(*GetProfileRequest)(nil),         // 0: user_service.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),        // 1: user_service.profile.v1.GetProfileResponse
	(*GetMyProfilesRequest)(nil),      // 2: user_service.profile.v1.GetMyProfilesRequest
	(*GetMyProfilesResponse)(nil),     // 3: user_service.profile.v1.GetMyProfilesResponse
	(*UpdateProfileRequest)(nil),      // 4: user_service.profile.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),     // 5: user_service.profile.v1.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),      // 6: user_service.profile.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),     // 7: user_service.profile.v1.DeleteProfileResponse
	(*UpdateDisplayNameRequest)(nil),  // 8: user_service.profile.v1.UpdateDisplayNameRequest
	(*UpdateDisplayNameResponse)(nil), // 9: user_service.profile.v1.UpdateDisplayNameResponse
	(*UpdateNameRequest)(nil),         // 10: user_service.profile.v1.UpdateNameRequest
	(*UpdateNameResponse)(nil),        // 11: user_service.profile.v1.UpdateNameResponse
	(*UpdateAvatarUrlRequest)(nil),    // 12: user_service.profile.v1.UpdateAvatarUrlRequest
	(*UpdateAvatarUrlResponse)(nil),   // 13: user_service.profile.v1.UpdateAvatarUrlResponse
	(*v1.UUID)(nil),                   // 14: common.v1.UUID
	(*v11.Profile)(nil),               // 15: user_service.v1.Profile
	(*v1.Token)(nil),                  // 16: common.v1.Token
	(*v1.RequestMetadata)(nil),        // 17: common.v1.RequestMetadata
	(*v1.Name)(nil),                   // 18: common.v1.Name
	(*v1.Url)(nil),                    // 19: common.v1.Url
}
var file_user_service_profile_v1_messages_proto_depIdxs = []int32{
	14, // 0: user_service.profile.v1.GetProfileRequest.profile_id:type_name -> common.v1.UUID
	15, // 1: user_service.profile.v1.GetProfileResponse.profile:type_name -> user_service.v1.Profile
	16, // 2: user_service.profile.v1.GetMyProfilesRequest.access_token:type_name -> common.v1.Token
	17, // 3: user_service.profile.v1.GetMyProfilesRequest.metadata:type_name -> common.v1.RequestMetadata
	15, // 4: user_service.profile.v1.GetMyProfilesResponse.profiles:type_name -> user_service.v1.Profile
	16, // 5: user_service.profile.v1.UpdateProfileRequest.access_token:type_name -> common.v1.Token
	14, // 6: user_service.profile.v1.UpdateProfileRequest.profile_id:type_name -> common.v1.UUID
	18, // 7: user_service.profile.v1.UpdateProfileRequest.first_name:type_name -> common.v1.Name
	18, // 8: user_service.profile.v1.UpdateProfileRequest.last_name:type_name -> common.v1.Name
	18, // 9: user_service.profile.v1.UpdateProfileRequest.display_name:type_name -> common.v1.Name
	19, // 10: user_service.profile.v1.UpdateProfileRequest.avatar_url:type_name -> common.v1.Url
	17, // 11: user_service.profile.v1.UpdateProfileRequest.metadata:type_name -> common.v1.RequestMetadata
	15, // 12: user_service.profile.v1.UpdateProfileResponse.profile:type_name -> user_service.v1.Profile
	16, // 13: user_service.profile.v1.DeleteProfileRequest.access_token:type_name -> common.v1.Token
	14, // 14: user_service.profile.v1.DeleteProfileRequest.profile_id:type_name -> common.v1.UUID
	17, // 15: user_service.profile.v1.DeleteProfileRequest.metadata:type_name -> common.v1.RequestMetadata
	16, // 16: user_service.profile.v1.UpdateDisplayNameRequest.access_token:type_name -> common.v1.Token
	14, // 17: user_service.profile.v1.UpdateDisplayNameRequest.profile_id:type_name -> common.v1.UUID
	18, // 18: user_service.profile.v1.UpdateDisplayNameRequest.display_name:type_name -> common.v1.Name
	17, // 19: user_service.profile.v1.UpdateDisplayNameRequest.metadata:type_name -> common.v1.RequestMetadata
	15, // 20: user_service.profile.v1.UpdateDisplayNameResponse.profile:type_name -> user_service.v1.Profile
	16, // 21: user_service.profile.v1.UpdateNameRequest.access_token:type_name -> common.v1.Token
	14, // 22: user_service.profile.v1.UpdateNameRequest.profile_id:type_name -> common.v1.UUID
	18, // 23: user_service.profile.v1.UpdateNameRequest.first_name:type_name -> common.v1.Name
	18, // 24: user_service.profile.v1.UpdateNameRequest.last_name:type_name -> common.v1.Name
	17, // 25: user_service.profile.v1.UpdateNameRequest.metadata:type_name -> common.v1.RequestMetadata
	15, // 26: user_service.profile.v1.UpdateNameResponse.profile:type_name -> user_service.v1.Profile
	16, // 27: user_service.profile.v1.UpdateAvatarUrlRequest.access_token:type_name -> common.v1.Token
	14, // 28: user_service.profile.v1.UpdateAvatarUrlRequest.profile_id:type_name -> common.v1.UUID
	19, // 29: user_service.profile.v1.UpdateAvatarUrlRequest.avatar_url:type_name -> common.v1.Url
	17, // 30: user_service.profile.v1.UpdateAvatarUrlRequest.metadata:type_name -> common.v1.RequestMetadata
	15, // 31: user_service.profile.v1.UpdateAvatarUrlResponse.profile:type_name -> user_service.v1.Profile
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_user_service_profile_v1_messages_proto_init() }
func file_user_service_profile_v1_messages_proto_init() {
	if File_user_service_profile_v1_messages_proto != nil {
		return
	}
	file_user_service_profile_v1_messages_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_profile_v1_messages_proto_rawDesc), len(file_user_service_profile_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_service_profile_v1_messages_proto_goTypes,
		DependencyIndexes: file_user_service_profile_v1_messages_proto_depIdxs,
		MessageInfos:      file_user_service_profile_v1_messages_proto_msgTypes,
	}.Build()
	File_user_service_profile_v1_messages_proto = out.File
	file_user_service_profile_v1_messages_proto_goTypes = nil
	file_user_service_profile_v1_messages_proto_depIdxs = nil
}
