// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user_service/profile/v1/service.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_profile_v1_service_proto protoreflect.FileDescriptor

const file_user_service_profile_v1_service_proto_rawDesc = "" +
	"\n" +
	"%user_service/profile/v1/service.proto\x12\x17user_service.profile.v1\x1a&user_service/profile/v1/messages.proto2\xa0\x06\n" +
	"\x0eProfileService\x12e\n" +
	"\n" +
	"GetProfile\x12*.user_service.profile.v1.GetProfileRequest\x1a+.user_service.profile.v1.GetProfileResponse\x12n\n" +
	"\rGetMyProfiles\x12-.user_service.profile.v1.GetMyProfilesRequest\x1a..user_service.profile.v1.GetMyProfilesResponse\x12n\n" +
	"\rUpdateProfile\x12-.user_service.profile.v1.UpdateProfileRequest\x1a..user_service.profile.v1.UpdateProfileResponse\x12n\n" +
	"\rDeleteProfile\x12-.user_service.profile.v1.DeleteProfileRequest\x1a..user_service.profile.v1.DeleteProfileResponse\x12z\n" +
	"\x11UpdateDisplayName\x121.user_service.profile.v1.UpdateDisplayNameRequest\x1a2.user_service.profile.v1.UpdateDisplayNameResponse\x12e\n" +
	"\n" +
	"UpdateName\x12*.user_service.profile.v1.UpdateNameRequest\x1a+.user_service.profile.v1.UpdateNameResponse\x12t\n" +
	"\x0fUpdateAvatarUrl\x12/.user_service.profile.v1.UpdateAvatarUrlRequest\x1a0.user_service.profile.v1.UpdateAvatarUrlResponseB\xef\x01\n" +
	"\x1bcom.user_service.profile.v1B\fServiceProtoP\x01ZHgithub.com/rijum8906/relay/packages/pb/user_service/profile/v1;profilev1\xa2\x02\x03UPX\xaa\x02\x16UserService.Profile.V1\xca\x02\x16UserService\\Profile\\V1\xe2\x02\"UserService\\Profile\\V1\\GPBMetadata\xea\x02\x18UserService::Profile::V1b\x06proto3"

var file_user_service_profile_v1_service_proto_goTypes = []any{
	(*GetProfileRequest)(nil),         // 0: user_service.profile.v1.GetProfileRequest
	(*GetMyProfilesRequest)(nil),      // 1: user_service.profile.v1.GetMyProfilesRequest
	(*UpdateProfileRequest)(nil),      // 2: user_service.profile.v1.UpdateProfileRequest
	(*DeleteProfileRequest)(nil),      // 3: user_service.profile.v1.DeleteProfileRequest
	(*UpdateDisplayNameRequest)(nil),  // 4: user_service.profile.v1.UpdateDisplayNameRequest
	(*UpdateNameRequest)(nil),         // 5: user_service.profile.v1.UpdateNameRequest
	(*UpdateAvatarUrlRequest)(nil),    // 6: user_service.profile.v1.UpdateAvatarUrlRequest
	(*GetProfileResponse)(nil),        // 7: user_service.profile.v1.GetProfileResponse
	(*GetMyProfilesResponse)(nil),     // 8: user_service.profile.v1.GetMyProfilesResponse
	(*UpdateProfileResponse)(nil),     // 9: user_service.profile.v1.UpdateProfileResponse
	(*DeleteProfileResponse)(nil),     // 10: user_service.profile.v1.DeleteProfileResponse
	(*UpdateDisplayNameResponse)(nil), // 11: user_service.profile.v1.UpdateDisplayNameResponse
	(*UpdateNameResponse)(nil),        // 12: user_service.profile.v1.UpdateNameResponse
	(*UpdateAvatarUrlResponse)(nil),   // 13: user_service.profile.v1.UpdateAvatarUrlResponse
}
var file_user_service_profile_v1_service_proto_depIdxs = []int32{
	0,  // 0: user_service.profile.v1.ProfileService.GetProfile:input_type -> user_service.profile.v1.GetProfileRequest
	1,  // 1: user_service.profile.v1.ProfileService.GetMyProfiles:input_type -> user_service.profile.v1.GetMyProfilesRequest
	2,  // 2: user_service.profile.v1.ProfileService.UpdateProfile:input_type -> user_service.profile.v1.UpdateProfileRequest
	3,  // 3: user_service.profile.v1.ProfileService.DeleteProfile:input_type -> user_service.profile.v1.DeleteProfileRequest
	4,  // 4: user_service.profile.v1.ProfileService.UpdateDisplayName:input_type -> user_service.profile.v1.UpdateDisplayNameRequest
	5,  // 5: user_service.profile.v1.ProfileService.UpdateName:input_type -> user_service.profile.v1.UpdateNameRequest
	6,  // 6: user_service.profile.v1.ProfileService.UpdateAvatarUrl:input_type -> user_service.profile.v1.UpdateAvatarUrlRequest
	7,  // 7: user_service.profile.v1.ProfileService.GetProfile:output_type -> user_service.profile.v1.GetProfileResponse
	8,  // 8: user_service.profile.v1.ProfileService.GetMyProfiles:output_type -> user_service.profile.v1.GetMyProfilesResponse
	9,  // 9: user_service.profile.v1.ProfileService.UpdateProfile:output_type -> user_service.profile.v1.UpdateProfileResponse
	10, // 10: user_service.profile.v1.ProfileService.DeleteProfile:output_type -> user_service.profile.v1.DeleteProfileResponse
	11, // 11: user_service.profile.v1.ProfileService.UpdateDisplayName:output_type -> user_service.profile.v1.UpdateDisplayNameResponse
	12, // 12: user_service.profile.v1.ProfileService.UpdateName:output_type -> user_service.profile.v1.UpdateNameResponse
	13, // 13: user_service.profile.v1.ProfileService.UpdateAvatarUrl:output_type -> user_service.profile.v1.UpdateAvatarUrlResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_profile_v1_service_proto_init() }
func file_user_service_profile_v1_service_proto_init() {
	if File_user_service_profile_v1_service_proto != nil {
		return
	}
	file_user_service_profile_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_profile_v1_service_proto_rawDesc), len(file_user_service_profile_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_profile_v1_service_proto_goTypes,
		DependencyIndexes: file_user_service_profile_v1_service_proto_depIdxs,
	}.Build()
	File_user_service_profile_v1_service_proto = out.File
	file_user_service_profile_v1_service_proto_goTypes = nil
	file_user_service_profile_v1_service_proto_depIdxs = nil
}
