// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: organization_service/org_team/v1/request.proto

package org_teamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrgTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgTeamRequest) Reset() {
	*x = CreateOrgTeamRequest{}
	mi := &file_organization_service_org_team_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgTeamRequest) ProtoMessage() {}

func (x *CreateOrgTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_org_team_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgTeamRequest) Descriptor() ([]byte, []int) {
	return file_organization_service_org_team_v1_request_proto_rawDescGZIP(), []int{0}
}

type UpdateOrgTeamNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrgTeamNameRequest) Reset() {
	*x = UpdateOrgTeamNameRequest{}
	mi := &file_organization_service_org_team_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrgTeamNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrgTeamNameRequest) ProtoMessage() {}

func (x *UpdateOrgTeamNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_org_team_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrgTeamNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrgTeamNameRequest) Descriptor() ([]byte, []int) {
	return file_organization_service_org_team_v1_request_proto_rawDescGZIP(), []int{1}
}

var File_organization_service_org_team_v1_request_proto protoreflect.FileDescriptor

const file_organization_service_org_team_v1_request_proto_rawDesc = "" +
	"\n" +
	".organization_service/org_team/v1/request.proto\x12 organization_service.org_team.v1\"\x16\n" +
	"\x14CreateOrgTeamRequest\"\x1a\n" +
	"\x18UpdateOrgTeamNameRequestB\xa2\x02\n" +
	"$com.organization_service.org_team.v1B\fRequestProtoP\x01ZRgithub.com/rijum8906/relay/packages/pb/organization_service/org_team/v1;org_teamv1\xa2\x02\x03OOX\xaa\x02\x1eOrganizationService.OrgTeam.V1\xca\x02\x1eOrganizationService\\OrgTeam\\V1\xe2\x02*OrganizationService\\OrgTeam\\V1\\GPBMetadata\xea\x02 OrganizationService::OrgTeam::V1b\x06proto3"

var (
	file_organization_service_org_team_v1_request_proto_rawDescOnce sync.Once
	file_organization_service_org_team_v1_request_proto_rawDescData []byte
)

func file_organization_service_org_team_v1_request_proto_rawDescGZIP() []byte {
	file_organization_service_org_team_v1_request_proto_rawDescOnce.Do(func() {
		file_organization_service_org_team_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_service_org_team_v1_request_proto_rawDesc), len(file_organization_service_org_team_v1_request_proto_rawDesc)))
	})
	return file_organization_service_org_team_v1_request_proto_rawDescData
}

var file_organization_service_org_team_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_organization_service_org_team_v1_request_proto_goTypes = []any{
	(*CreateOrgTeamRequest)(nil),     // 0: organization_service.org_team.v1.CreateOrgTeamRequest
	(*UpdateOrgTeamNameRequest)(nil), // 1: organization_service.org_team.v1.UpdateOrgTeamNameRequest
}
var file_organization_service_org_team_v1_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_organization_service_org_team_v1_request_proto_init() }
func file_organization_service_org_team_v1_request_proto_init() {
	if File_organization_service_org_team_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_service_org_team_v1_request_proto_rawDesc), len(file_organization_service_org_team_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_service_org_team_v1_request_proto_goTypes,
		DependencyIndexes: file_organization_service_org_team_v1_request_proto_depIdxs,
		MessageInfos:      file_organization_service_org_team_v1_request_proto_msgTypes,
	}.Build()
	File_organization_service_org_team_v1_request_proto = out.File
	file_organization_service_org_team_v1_request_proto_goTypes = nil
	file_organization_service_org_team_v1_request_proto_depIdxs = nil
}
