// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: organization_service/org_team/v1/response.proto

package org_teamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgTeamRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrgTeamRes) Reset() {
	*x = OrgTeamRes{}
	mi := &file_organization_service_org_team_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgTeamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgTeamRes) ProtoMessage() {}

func (x *OrgTeamRes) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_org_team_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgTeamRes.ProtoReflect.Descriptor instead.
func (*OrgTeamRes) Descriptor() ([]byte, []int) {
	return file_organization_service_org_team_v1_response_proto_rawDescGZIP(), []int{0}
}

func (x *OrgTeamRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrgTeamRes) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrgTeamRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrgTeamRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OrgTeamListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*OrgTeamRes          `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgTeamListRes) Reset() {
	*x = OrgTeamListRes{}
	mi := &file_organization_service_org_team_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgTeamListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgTeamListRes) ProtoMessage() {}

func (x *OrgTeamListRes) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_org_team_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgTeamListRes.ProtoReflect.Descriptor instead.
func (*OrgTeamListRes) Descriptor() ([]byte, []int) {
	return file_organization_service_org_team_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *OrgTeamListRes) GetTeams() []*OrgTeamRes {
	if x != nil {
		return x.Teams
	}
	return nil
}

type TeamPermissionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamPermissionsRes) Reset() {
	*x = TeamPermissionsRes{}
	mi := &file_organization_service_org_team_v1_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamPermissionsRes) ProtoMessage() {}

func (x *TeamPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_organization_service_org_team_v1_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamPermissionsRes.ProtoReflect.Descriptor instead.
func (*TeamPermissionsRes) Descriptor() ([]byte, []int) {
	return file_organization_service_org_team_v1_response_proto_rawDescGZIP(), []int{2}
}

func (x *TeamPermissionsRes) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_organization_service_org_team_v1_response_proto protoreflect.FileDescriptor

const file_organization_service_org_team_v1_response_proto_rawDesc = "" +
	"\n" +
	"/organization_service/org_team/v1/response.proto\x12 organization_service.org_team.v1\"{\n" +
	"\n" +
	"OrgTeamRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"T\n" +
	"\x0eOrgTeamListRes\x12B\n" +
	"\x05teams\x18\x01 \x03(\v2,.organization_service.org_team.v1.OrgTeamResR\x05teams\"6\n" +
	"\x12TeamPermissionsRes\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissionsB\xa3\x02\n" +
	"$com.organization_service.org_team.v1B\rResponseProtoP\x01ZRgithub.com/rijum8906/relay/packages/pb/organization_service/org_team/v1;org_teamv1\xa2\x02\x03OOX\xaa\x02\x1eOrganizationService.OrgTeam.V1\xca\x02\x1eOrganizationService\\OrgTeam\\V1\xe2\x02*OrganizationService\\OrgTeam\\V1\\GPBMetadata\xea\x02 OrganizationService::OrgTeam::V1b\x06proto3"

var (
	file_organization_service_org_team_v1_response_proto_rawDescOnce sync.Once
	file_organization_service_org_team_v1_response_proto_rawDescData []byte
)

func file_organization_service_org_team_v1_response_proto_rawDescGZIP() []byte {
	file_organization_service_org_team_v1_response_proto_rawDescOnce.Do(func() {
		file_organization_service_org_team_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_service_org_team_v1_response_proto_rawDesc), len(file_organization_service_org_team_v1_response_proto_rawDesc)))
	})
	return file_organization_service_org_team_v1_response_proto_rawDescData
}

var file_organization_service_org_team_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_organization_service_org_team_v1_response_proto_goTypes = []any{
	(*OrgTeamRes)(nil),         // 0: organization_service.org_team.v1.OrgTeamRes
	(*OrgTeamListRes)(nil),     // 1: organization_service.org_team.v1.OrgTeamListRes
	(*TeamPermissionsRes)(nil), // 2: organization_service.org_team.v1.TeamPermissionsRes
}
var file_organization_service_org_team_v1_response_proto_depIdxs = []int32{
	0, // 0: organization_service.org_team.v1.OrgTeamListRes.teams:type_name -> organization_service.org_team.v1.OrgTeamRes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_organization_service_org_team_v1_response_proto_init() }
func file_organization_service_org_team_v1_response_proto_init() {
	if File_organization_service_org_team_v1_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_service_org_team_v1_response_proto_rawDesc), len(file_organization_service_org_team_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_service_org_team_v1_response_proto_goTypes,
		DependencyIndexes: file_organization_service_org_team_v1_response_proto_depIdxs,
		MessageInfos:      file_organization_service_org_team_v1_response_proto_msgTypes,
	}.Build()
	File_organization_service_org_team_v1_response_proto = out.File
	file_organization_service_org_team_v1_response_proto_goTypes = nil
	file_organization_service_org_team_v1_response_proto_depIdxs = nil
}
