syntax = "proto3";

package core.v1;

message RequestMetadata {
  string device_id = 1;
}

message EmptyRequest {}

message SuccessResponse {
  bool success = 1;
}

message EmailRequest {
  string email = 1;
}

message IDRequest {
  string id = 1;
}

message TokenHashRequest {
  string token_hash = 1;
}

message IDAndScopedTokenRequest {
  string token_scope = 1;
  string id = 2;
}

message PaginationRequest {
  int32 page = 1;
  int32 limit = 2;
}

message IDWithPaginationReq {
  string id = 1;
  core.v1.PaginationRequest pagination = 2;
}
