name: User Service Test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  TEST_DB_URL: "postgres://test_user:test_password@localhost:5433/test_db?sslmode=disable&search_path=public"

jobs:
  test-user-service:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"
          cache: true

      - name: Verify Go Version
        run: go version

      - name: Start Test docker-compose
        run: |
          docker compose -f docker-compose.test.yml up -d
          docker compose -f docker-compose.test.yml ps

      - name: Setup Workspace
        run: make setup

      - name: Install Dependencies
        run: go mod download

      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}

      - name: Run Migration
        working-directory: services/user-service
        run: |
          atlas migrate apply --url "${{ env.TEST_DB_URL }}" --dir "file://db/migrations" --allow-dirty

      - name: Run unit tests
        working-directory: services/user-service
        run: go test -v ./...
